<template>
 <DashboardLeafPanel id="payments-billing" title="Payments usage billing" :footer="false">
  <UAlert v-if="error" color="error" :description="error.message" /><USkeleton v-else-if="pending" class="h-24" />
  <template v-else-if="data"><p>Payments usage is billed postpaid through Metronome: 1.337% of captured volume plus actual attributable Stripe costs. Refunds and disputes retain the captured-volume fee.</p><p class="mt-3">Your operating billing customer and payment method are separate from customer purchases and your connected merchant account.</p>
   <UAlert v-if="data.configured===false" class="mt-4" color="warning" description="Payments usage billing is not configured. Accrued usage remains durably queued." /><UButton v-if="data.configured===false" class="mt-4" :loading="working" @click="provision">Set up postpaid Payments billing</UButton>
   <template v-else><p class="mt-4">Metronome contract {{ account.metronome_contract_id }} · {{ account.status }}</p><p class="text-sm text-muted">Native provider billing cadence, collection and grace settings apply. Servicing continues after downgrade; no new acceptance is granted.</p></template>
   <UButton v-if="['servicing','closing'].includes(String(account.status))" class="mt-4" :loading="working" variant="outline" @click="finalize">End historical Payments usage contract</UButton>
   <h3 class="mt-6 font-semibold">Accrued usage awaiting delivery</h3><p v-for="(row,i) in accrued" :key="i" class="mt-2">{{ paymentMoney(row.amount,String(row.currency).toUpperCase()) }} · {{ row.kind }} · {{ row.event_count }} events <span v-if="row.error">· {{ row.error }}</span></p><p v-if="!accrued.length">No undelivered usage.</p>
   <h3 class="mt-6 font-semibold">Metronome invoices</h3><UCard v-for="row in invoices" :key="String(row.id)" class="mt-3">{{ row.id }} · {{ row.status }} · {{ row.total }} provider pricing units<p class="text-sm text-muted">{{ row.start_timestamp }} → {{ row.end_timestamp }}</p></UCard>
   <template v-if="credits.length"><h3 class="mt-6 font-semibold">Actual-cost credits requiring native settlement</h3><p class="mt-2 text-sm">For a finalized period, issue the credit in the operating Stripe account’s native billing dashboard. Refund a paid invoice or reduce an unpaid invoice there, including any native tax handling. Reconcile the issued credit note here; the credit remains visible until verified.</p><UButton class="mt-3" to="https://dashboard.stripe.com/invoices" target="_blank" variant="outline">Open Stripe billing credits</UButton><UCard v-for="row in credits" :key="String(row.id)" class="mt-3"><p>{{ row.currency }} {{ -Number(row.amount) }} · {{ row.source_id }}</p><UInput v-model="creditNotes[String(row.id)]" class="mt-3" placeholder="Issued Stripe credit note ID" /><UButton class="mt-3 ml-2" :loading="working" @click="settle(String(row.id))">Verify native credit settlement</UButton></UCard></template>
  </template><UAlert v-if="failure" class="mt-4" color="error" :description="failure" />
 </DashboardLeafPanel>
</template>
<script setup lang="ts">
import {paymentMoney} from '~/shared/payment-display'
definePageMeta({layout:'dashboard'})
const route=useRoute(),api=useDashboardApi(),working=ref(false),failure=ref(''),creditNotes=ref<Record<string,string>>({})
const {data,pending,error,refresh}=await useAsyncData(()=>`payments-billing:${route.params.orgSlug}`,()=>api<Record<string,unknown>>('/api/dashboard/payments/billing',{validate:(v:unknown):v is Record<string,unknown>=>isRecord(v)}),{lazy:true})
const rows=(v:unknown)=>Array.isArray(v)?v.filter(isRecord):[]
const account=computed(()=>isRecord(data.value?.account)?data.value.account:{}),accrued=computed(()=>rows(data.value?.pending)),invoices=computed(()=>rows(data.value?.invoices)),credits=computed(()=>rows(data.value?.credits))
async function finalize(){working.value=true;failure.value='';try{await api('/api/dashboard/payments/billing',{method:'POST',body:{action:'finalize'},validate:(v:unknown):v is Record<string,unknown>=>isRecord(v)&&v.closed===true});await refresh()}catch(error){failure.value=getErrorMessage(error,'Historical contract could not be ended')}finally{working.value=false}}
async function provision(){working.value=true;failure.value='';try{await api('/api/dashboard/payments/billing',{method:'POST',body:{action:'provision'},validate:(v:unknown):v is Record<string,unknown>=>isRecord(v)&&typeof v.metronome_contract_id==='string'});await refresh()}catch(error){failure.value=getErrorMessage(error,'Payments billing setup failed')}finally{working.value=false}}
async function settle(id:string){working.value=true;failure.value='';try{await api('/api/dashboard/payments/billing',{method:'POST',body:{action:'reconcile_credit',event_id:id,credit_note_id:creditNotes.value[id]},validate:(v:unknown):v is Record<string,unknown>=>isRecord(v)&&v.settled===true});await refresh()}catch(error){failure.value=getErrorMessage(error,'Native credit could not be reconciled')}finally{working.value=false}}
</script>
