name = "krabiclaw-ai"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "REVIEWS_DB"
database_name = "thaiclaw-reviews"
database_id = "57cc9c44-1a23-41c3-8ec9-6b404c12ca2c"
