import { expect, request as playwrightRequest, test } from '@playwright/test'
import { loginAs } from './helpers/auth'
import { waitForNuxtHydration } from './helpers'
import { mcpData, mcpRequest } from './helpers/mcp'
import { blawbyTestExtraHeaders } from './test-env'

test.use({ timezoneId: 'America/New_York' })

test('native online review uses canonical Products, holds capacity, and releases it once', async ({ page, request, baseURL }) => {
  test.setTimeout(120_000)
  test.skip(process.env.NATIVE_CONSULTATION_PROOF !== 'true' || !['localhost', '127.0.0.1'].includes(new URL(baseURL!).hostname), 'Explicit opt-in in an isolated disposable checkout only; never mutate shared suite fixtures')
  const analyticsFailures: string[] = []
  page.on('response', response => {
    if (/\/api\/(analytics\/track|public\/conversion-events)$/.test(new URL(response.url()).pathname) && response.status() >= 400) analyticsFailures.push(`${response.status()} ${response.url()}`)
  })
  await loginAs(page.request, baseURL!)
  const cleanupRequest = await playwrightRequest.newContext({ baseURL, storageState: await page.context().storageState() })
  const org = 'org-ncls-blawby'
  const editor = `/api/editor/organizations/${org}`
  const previous = await (await page.request.get(`${editor}/consultation`)).json()
  const serviceListResponse = await page.request.get(`${editor}/pages?locale=en`)
  expect(serviceListResponse.status(), await serviceListResponse.text()).toBe(200)
  const serviceRow = (await serviceListResponse.json()).pages.find((page: { path: string }) => page.path === '/services/family')
  expect(serviceRow).toBeTruthy()
  const service = (await (await page.request.get(`${editor}/pages/${serviceRow.id}`)).json()).page
  const writeBinding = async (api: typeof page.request, productId: string | null) => {
    const current = (await (await api.get(`${editor}/pages/${service.id}`)).json()).page
    const response = await api.patch(`${editor}/pages/${service.id}`, { data: { path: current.path, title: current.title, summary: current.summary, pageType: current.page_type, recipe: current.recipe, sortOrder: current.sort_order, blocks: current.blocks, expectedUpdatedAt: current.document.updated_at, productId } })
    expect(response.status(), await response.text()).toBe(200)
    expect((await response.json()).page.product_id).toBe(productId)
  }
  const stamp = Date.now()
  const products: Array<{ id: string; name: string; slug: string; variants: Array<{ id: string }> }> = []
  const tomorrow = new Date(Date.now() + 86400000)
  const day = tomorrow.toISOString().slice(0, 10)
  const headers = blawbyTestExtraHeaders()
  try {
  for (let index = 0; index < 2; index++) {
    const create = await page.request.post(`${editor}/products`, { data: { kind: 'service', details: { preparation: 'Bring a list of questions for your consultation', cancellation_policy: 'Contact us at least one day before your appointment to cancel.' }, name: `Local consultation ${stamp}-${index}`, description: 'A local test service for reviewing the native consultation flow.', variants: [{ name: 'Online', prices: [{ unit_amount: 0, currency: 'USD' }] }] } })
    expect(create.status(), await create.text()).toBe(201)
    const product = (await create.json()).product
    products.push(product)
    const config = await page.request.put(`${editor}/products/${product.id}/booking`, { data: { duration_minutes: 45, default_capacity: 1, confirmation_mode: 'review', online_payment_required: true, online_timezone: 'UTC', calendar_group: `local-${stamp}` } })
    expect(config.status(), await config.text()).toBe(200)
    const schedule = await page.request.put(`${editor}/products/${product.id}/availability`, { data: { location_id: null, slots: [{ weekday: tomorrow.getUTCDay(), start_time: '14:00' }] } })
    expect(schedule.status(), await schedule.text()).toBe(200)
    const publish = await page.request.put(`${editor}/products/${product.id}/publication`, { data: { published: true } })
    expect(publish.status(), await publish.text()).toBe(200)
  }
  const activate = await mcpRequest(page.request, baseURL!, { method: 'tools/call', toolName: 'set_consultation_mode', args: { organization_id: org, mode: 'native' } })
  expect(activate.status(), await activate.text()).toBe(200)
  expect(mcpData<{ settings: { mode: string } }>(await activate.json()).settings.mode).toBe('native')
  expect((await (await page.request.get(`${editor}/consultation`)).json()).mode).toBe('native')
    await page.goto(`/dashboard/north-carolina-legal-services/products/${products[0]!.id}/booking`)
    const bookingPath = `/dashboard/north-carolina-legal-services/products/${products[0]!.id}/booking`
    await expect(page.getByRole('link', { name: 'Guest limit One guest per session' })).toBeVisible()
    // The Calendar-only build saves assignment in the focused CMS editor and
    // reads it through MCP without requiring Payments tables or Checkout.
    const membersResponse = await page.request.get(`/api/organizations/${org}/members/scheduling`)
    expect(membersResponse.status(), await membersResponse.text()).toBe(200)
    const self = (await membersResponse.json()).members.find((member: { self: boolean }) => member.self)
    expect(self).toBeTruthy()
    await page.getByRole('link', { name: 'Who guests meet Tenant organization', exact: true }).click()
    await page.getByRole('combobox').click()
    await page.getByRole('option', { name: self.name, exact: true }).click()
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Who guests meet Assigned team member', exact: true })).toBeVisible()
    const assigned = await mcpRequest(page.request, baseURL!, { method: 'tools/call', toolName: 'get_product', args: { organization_id: org, product_id: products[0]!.id } })
    expect(assigned.status(), await assigned.text()).toBe(200)
    expect(mcpData<{ product: { booking: Record<string, unknown> } }>(await assigned.json()).product.booking).toMatchObject({ scheduling_mode: 'provider', assigned_member_id: self.id })
    await page.getByRole('link', { name: 'Who guests meet Assigned team member', exact: true }).click()
    await page.getByRole('combobox').click()
    await page.getByRole('option', { name: 'Tenant organization', exact: true }).click()
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Who guests meet Tenant organization', exact: true })).toBeVisible()

    await page.getByRole('link', { name: 'Duration 45 minutes', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeDisabled()
    await page.getByLabel('Duration in minutes', { exact: true }).fill('50')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Duration 50 minutes', exact: true })).toBeVisible()
    const readConfig = async () => {
      const result = await mcpRequest(page.request, baseURL!, { method: 'tools/call', toolName: 'get_product', args: { organization_id: org, product_id: products[0]!.id } })
      expect(result.status()).toBe(200)
      return mcpData<{ product: { booking: Record<string, unknown> } }>(await result.json()).product.booking
    }
    expect(await readConfig()).toMatchObject({ duration_minutes: 50, default_capacity: 1, confirmation_mode: 'review', online_payment_required: true, online_timezone: 'UTC', calendar_group: `local-${stamp}` })
    expect((await (await page.request.get(`${editor}/consultation`)).json()).mode).toBe('native')
    const retainedSchedule = await page.request.get(`${editor}/products/${products[0]!.id}/availability?location_id=online`)
    expect(retainedSchedule.status()).toBe(200)
    expect((await retainedSchedule.json()).rules).toHaveLength(1)
    await page.getByRole('link', { name: 'Duration 50 minutes', exact: true }).click()
    await page.getByLabel('Duration in minutes', { exact: true }).fill('45')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Duration 45 minutes', exact: true })).toBeVisible()
    await page.getByRole('link', { name: /^Meeting location Online · UTC · GMT(?:\+0)?$/ }).click()
    const timeZone = page.getByRole('button', { name: 'Time zone', exact: true })
    await expect(timeZone).toContainText('UTC · GMT')
    await timeZone.click()
    await page.getByPlaceholder('Search by city, e.g. Bangkok').fill('New York')
    await page.getByRole('option', { name: /^New York · GMT/ }).click()
    await expect(timeZone).toContainText('New York')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('link', { name: /^Meeting location Online · New York · GMT/ })).toBeVisible()
    expect(await readConfig()).toMatchObject({ online_timezone: 'America/New_York', duration_minutes: 45, calendar_group: `local-${stamp}` })
    // Restore the explicit UTC schedule used by the public booking assertions below.
    const restoredTimezone = await page.request.put(`${editor}/products/${products[0]!.id}/booking`, { data: { online_timezone: 'UTC' } })
    expect(restoredTimezone.status(), await restoredTimezone.text()).toBe(200)
    expect(await readConfig()).toMatchObject({ online_timezone: 'UTC' })
    await page.goto(`${bookingPath}/capacity`)
    await expect(page.getByRole('radio', { name: 'One guest', exact: true })).toBeChecked()
    await page.getByRole('radio', { name: 'A group of guests', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeDisabled()
    await page.getByLabel('Maximum guests per session', { exact: true }).fill('2')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Guest limit Up to 2 guests per session', exact: true })).toBeVisible()
    expect(await readConfig()).toMatchObject({ default_capacity: 2, duration_minutes: 45, online_timezone: 'UTC', online_payment_required: true })
    await page.getByRole('link', { name: 'Guest limit Up to 2 guests per session', exact: true }).click()
    await page.getByRole('radio', { name: 'One guest', exact: true }).click()
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Guest limit One guest per session', exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Guest limit One guest per session', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeDisabled()
    await page.screenshot({ path: '/tmp/pr1211-booking-setup.png', fullPage: true })
    const desktopViewport = page.viewportSize()!
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByRole('radio', { name: 'A group of guests', exact: true }).click()
    await page.getByLabel('Maximum guests per session', { exact: true }).fill('3')
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(page).toHaveURL(`${baseURL}${bookingPath}`)
    await expect(page.getByRole('link', { name: 'Guest limit One guest per session', exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Guest limit One guest per session', exact: true }).click()
    await expect(page.getByRole('radio', { name: 'One guest', exact: true })).toBeChecked()
    await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeDisabled()
    expect(await readConfig()).toMatchObject({ default_capacity: 1 })
    await page.screenshot({ path: '/tmp/pr1211-booking-mobile.png', fullPage: true })
    await page.setViewportSize(desktopViewport)
    const bindViaMcp = async (productId?: string | null) => {
      const current = (await (await page.request.get(`${editor}/pages/${service.id}`)).json()).page
      const response = await mcpRequest(page.request, baseURL!, { method: 'tools/call', toolName: 'update_site_page', args: {
        organization_id: org, variant_id: service.id, expected_updated_at: current.document.updated_at,
        path: current.path, title: current.title, summary: current.summary, pageType: current.page_type,
        recipe: current.recipe, sortOrder: current.sort_order,
        blocks: current.blocks.map((block: { id: string; type: string; level: number | null; parent_block_id: string | null; source_block_id: string | null; data: Record<string, unknown> }) => ({
          id: block.id, type: block.type, level: block.level, parent_block_id: block.parent_block_id, source_block_id: block.source_block_id, data: block.data,
        })),
        ...(productId === undefined ? {} : { product_id: productId }),
      } })
      expect(response.status(), await response.text()).toBe(200)
      expect((await response.json()).result.isError).not.toBe(true)
    }
    await bindViaMcp(null)
    expect((await (await page.request.get(`${editor}/pages/${service.id}`)).json()).page.product_id).toBeNull()
    await bindViaMcp(products[0]!.id)
    await bindViaMcp()
    expect((await (await page.request.get(`${editor}/pages/${service.id}`)).json()).page.product_id).toBe(products[0]!.id)
    await bindViaMcp(null)
    await page.setExtraHTTPHeaders(headers)
    await page.goto(`/dashboard/north-carolina-legal-services/pages/${service.id}/booking`)
    const bindingSelector = page.getByRole('combobox', { name: 'Consultation Product' })
    await expect(bindingSelector).toBeVisible()
    await bindingSelector.click()
    await page.getByRole('option', { name: products[0]!.name, exact: true }).click()
    const bindingSaved = page.waitForResponse(response => new URL(response.url()).pathname.endsWith(`/pages/${service.id}`) && response.request().method() === 'PATCH')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    expect((await bindingSaved).status()).toBe(200)
    const preserved = (await (await page.request.get(`${editor}/pages/${service.id}`)).json()).page
    expect(preserved.product_id).toBe(products[0]!.id)
    // The canonical page update advances block timestamps; content, IDs and media must remain exact.
    const content = (blocks: Array<Record<string, unknown>>) => blocks.map(block => Object.fromEntries(Object.entries(block).filter(([key]) => key !== 'updated_at')))
    expect(content(preserved.blocks)).toEqual(content(service.blocks))
    expect(preserved.summary).toBe(service.summary)
    await page.goto(`/dashboard/north-carolina-legal-services/pages/${service.id}/booking`)
    await expect(bindingSelector).toContainText(products[0]!.name)
    await page.setExtraHTTPHeaders(headers)
    const wrongRoute = await request.get(`/experiences/${products[0]!.slug}`, { headers })
    expect(wrongRoute.status()).toBe(404)
    const publicBefore = await request.get(`/api/public/pages?path=${service.path}`, { headers })
    expect(publicBefore.status(), await publicBefore.text()).toBe(200)
    const publishedService = (await publicBefore.json()).page
    expect(publishedService.product_id).toBe(products[0]!.id)
    expect(publishedService.title).toBe(service.title)
    expect(publishedService.blocks.map((block: { id: string }) => block.id)).toEqual(service.blocks.map((block: { id: string }) => block.id))
    const storedGallery = (await Promise.all(['cover', 'gallery'].map(async slot => {
      const response = await page.request.get(`${editor}/media?ownerType=content_document&ownerId=${publishedService.id}&slot=${slot}`)
      expect(response.status(), await response.text()).toBe(200)
      return (await response.json()).media as Array<{ id: string; public_url: string; kind: string; thumbnail_url: string | null }>
    }))).flat()
    expect(storedGallery).toHaveLength(8)
    expect(publishedService.media.filter((media: { slot: string }) => ['cover', 'gallery'].includes(media.slot)).map((media: { asset_id: string }) => media.asset_id)).toEqual(storedGallery.map(media => media.id))
    await page.goto('/schedule')
    const serviceSelector = page.getByRole('combobox', { name: 'Service', exact: true })
    await expect(serviceSelector).toContainText(service.title)
    const chevronInset = await serviceSelector.evaluate(element => element.getBoundingClientRect().right - element.querySelector('[data-slot="trailingIcon"]')!.getBoundingClientRect().right)
    expect(chevronInset).toBeGreaterThanOrEqual(10)
    await serviceSelector.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('option', { name: service.title, exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(serviceSelector).toBeFocused()
    await expect(page.getByRole('heading', { name: service.title, exact: true })).toBeVisible()
    await expect(page.getByText('Free', { exact: true }).filter({ visible: true })).toBeVisible()
    await expect(page.getByText('Staff review', { exact: true }).first()).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Upcoming availability', exact: true })).toBeVisible()
    const pageTimezone = page.getByRole('button', { name: 'Time zone', exact: true })
    await expect(pageTimezone).toContainText('(America/New_York)')
    await pageTimezone.click()
    const timezonePopup = page.getByRole('listbox')
    const supportedZones = await page.evaluate(() => [...new Set(['UTC', ...Intl.supportedValuesOf('timeZone')])].sort())
    await expect(timezonePopup.getByRole('option')).toHaveCount(supportedZones.length)
    expect((await timezonePopup.getByRole('option').allTextContents()).map(label => label.match(/\(([^)]+)\)$/)![1]).sort()).toEqual(supportedZones)
    const popupBox = await timezonePopup.boundingBox()
    expect(popupBox!.height).toBeLessThanOrEqual(241)
    const zoneViewport = timezonePopup.locator('[data-slot="viewport"]')
    const initialScroll = await zoneViewport.evaluate(element => element.scrollTop)
    await zoneViewport.hover()
    await page.mouse.wheel(0, 140)
    await expect.poll(() => zoneViewport.evaluate(element => element.scrollTop)).toBeGreaterThan(initialScroll)
    const zoneSearch = page.getByLabel('Search time zones', { exact: true })
    await zoneSearch.fill('UTC')
    await expect(timezonePopup.getByRole('option')).toHaveCount(1)
    await zoneSearch.press('ArrowDown')
    await zoneSearch.press('Enter')
    await expect(pageTimezone).toContainText('(UTC)')
    await pageTimezone.click()
    await zoneSearch.fill('America/New_York')
    await expect(timezonePopup.getByRole('option')).toHaveCount(1)
    await zoneSearch.press('ArrowDown')
    await zoneSearch.press('Enter')
    await expect(pageTimezone).toContainText('(America/New_York)')
    await expect(page.locator('a[href*="/experiences/"]')).toHaveCount(0)
    await expect(page.locator('section[aria-label="Choose your consultation"] img')).toHaveAttribute('alt', publishedService.media.find((media: { slot: string }) => media.slot === 'cover').alt_text ?? '')
    await expect.poll(() => page.locator('section[aria-label="Choose your consultation"] img').evaluateAll(images => images.every(image => (image as HTMLImageElement).naturalWidth > 0))).toBe(true)
    await page.setViewportSize({ width: 390, height: 844 })
    await page.setViewportSize({ width: 1280, height: 720 })
    await page.getByRole('link', { name: 'Full service details →', exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`${service.path}$`))
    await expect(page.getByRole('heading', { name: service.title, exact: true, level: 1 })).toBeVisible()
    await expect(page.locator('[data-block-type="hero"]')).toHaveCount(0)
    await expect(page.getByRole('heading', { name: /where.*meet/i })).toHaveCount(0)
    await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', new URL(service.path, baseURL).href)
    expect(await page.locator('[data-tenant-page] [data-block-type]').evaluateAll(blocks => blocks.map(block => block.getAttribute('data-block-type')))).toEqual(service.blocks.filter((block: { type: string }) => block.type !== 'hero').map((block: { type: string }) => block.type))
    const gallery = publishedService.media.filter((media: { slot: string; public_url: string | null }) => ['cover', 'gallery'].includes(media.slot) && media.public_url)
    // This existing fixture has one cover and seven authored gallery placements.
    expect(gallery).toHaveLength(8)
    expect(gallery.map((media: { public_url: string; kind: string; thumbnail_url: string | null }) => ({ url: media.public_url, kind: media.kind, poster: media.thumbnail_url }))).toEqual(storedGallery.map(media => ({ url: media.public_url, kind: media.kind, poster: media.thumbnail_url })))
    const visibleTiles = page.locator('[data-media-gallery] button')
    await expect(visibleTiles).toHaveCount(4)
    const tileBounds = await visibleTiles.evaluateAll(tiles => tiles.map(tile => { const box = tile.getBoundingClientRect(); const frame = tile.closest('[data-media-gallery]')!.getBoundingClientRect(); return { top: box.top - frame.top, bottom: box.bottom - frame.top, height: frame.height } }))
    expect(tileBounds.every(tile => tile.top >= 0 && tile.bottom <= tile.height + 1)).toBe(true)
    const lightbox = page.getByRole('dialog', { name: service.title, exact: true })
    for (let index = 0; index < 4; index++) {
      await visibleTiles.nth(index).click()
      await expect(lightbox.locator('section').nth(index).locator('img').last()).toBeInViewport()
      await lightbox.getByRole('button', { name: 'Close', exact: true }).click()
    }
    await visibleTiles.first().click()
    for (let index = 0; index < gallery.length; index++) {
      const image = lightbox.locator('section').nth(index).locator('img').last()
      await expect(image).toHaveAttribute('src', gallery[index].public_url)
      await expect(image).toHaveAttribute('alt', gallery[index].alt_text ?? '')
      await expect(image).toBeInViewport()
      await expect.poll(() => image.evaluate(element => (element as HTMLImageElement).complete && (element as HTMLImageElement).naturalWidth > 0), { timeout: 30_000 }).toBe(true)
      if (index < gallery.length - 1) await lightbox.getByRole('button', { name: 'Next media', exact: true }).click()
    }
    await lightbox.getByRole('button', { name: 'Close', exact: true }).click()
    const placement = await page.locator('#consultations, [data-tenant-page]').evaluateAll(elements => elements.map(element => element.getBoundingClientRect().top))
    expect(placement[0]).toBeLessThan(placement[1]!)
    const externalUrl = 'https://example.com/?booking=ncls'
    await page.setExtraHTTPHeaders({})
    await page.goto(`/dashboard/north-carolina-legal-services/products/${products[0]!.id}/order-url`)
    await page.getByLabel('Website address', { exact: true }).fill(externalUrl)
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    const nativeConfigBeforeHandoff = await readConfig()
    const withoutNativeCalendar = await page.request.put(`${editor}/products/${products[0]!.id}/booking`, { data: { online_timezone: null, calendar_group: null } })
    expect(withoutNativeCalendar.status(), await withoutNativeCalendar.text()).toBe(200)
    const externalProduct = await mcpRequest(page.request, baseURL!, { method: 'tools/call', toolName: 'get_product', args: { organization_id: org, product_id: products[0]!.id } })
    const savedExternalProduct = mcpData<{ product: { order_url: string; booking: { online_timezone: string | null } } }>(await externalProduct.json()).product
    expect(savedExternalProduct.order_url).toBe(externalUrl)
    expect(savedExternalProduct.booking.online_timezone).toBeNull()
    expect(savedExternalProduct).not.toHaveProperty('tags')
    const externalSessions = await request.get(`/api/public/products/${products[0]!.slug}/sessions?location_id=online`, { headers })
    expect(externalSessions.status()).toBe(200)
    expect((await externalSessions.json()).sessions).toEqual([])
    await page.setExtraHTTPHeaders(headers)
    await page.goto(service.path)
    await expect(page.getByRole('heading', { name: service.title, exact: true, level: 1 })).toBeVisible()
    for (const width of [1280, 390]) {
      await page.setViewportSize({ width, height: 844 })
      const handoff = page.locator(`a[href="${externalUrl}"]:visible`)
      await expect(handoff).toHaveCount(1)
      await expect(handoff).toHaveText('Book now')
      await expect(page.getByRole('button', { name: 'Request appointment', exact: true })).toHaveCount(0)
    }
    await waitForNuxtHydration(page)
    const recordedHandoff = page.waitForResponse(response => new URL(response.url()).pathname === '/api/public/conversion-events' && response.request().postDataJSON()?.event_name === 'product_order_external_click')
    const externalTab = page.waitForEvent('popup')
    await page.locator(`a[href="${externalUrl}"]:visible`).click()
    expect((await recordedHandoff).status()).toBe(201)
    const destination = await externalTab
    await expect(destination).toHaveURL(externalUrl)
    await destination.close()
    const events = await mcpRequest(page.request, baseURL!, { method: 'tools/call', toolName: 'query_organization_analytics', args: { organization_id: org, mode: 'events', filters: { event_name: 'product_order_external_click', entity_id: products[0]!.id } } })
    const recordedEvents = mcpData<{ rows: Array<Record<string, unknown>> }>(await events.json()).rows
    expect(recordedEvents).toHaveLength(1)
    expect(recordedEvents[0]).toMatchObject({ location_id: null, subject: { type: 'product', id: products[0]!.id }, metadata: { destination_hostname: 'example.com' } })
    const restoreCalendar = await page.request.put(`${editor}/products/${products[0]!.id}/booking`, { data: { online_timezone: nativeConfigBeforeHandoff.online_timezone, calendar_group: nativeConfigBeforeHandoff.calendar_group } })
    expect(restoreCalendar.status(), await restoreCalendar.text()).toBe(200)
    const restoreNative = await page.request.patch(`${editor}/products/${products[0]!.id}`, { data: { order_url: null } })
    expect(restoreNative.status()).toBe(200)
    await page.goto(service.path)
    await expect(page.getByText('Bring a list of questions for your consultation', { exact: true })).toBeVisible()
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(page.getByRole('button', { name: 'Request appointment', exact: true })).toBeVisible()
    await page.setViewportSize({ width: 1280, height: 720 })
    await page.getByRole('button', { name: 'Request appointment', exact: true }).focus()
    await page.keyboard.press('Enter')
    const bookingDialog = page.getByRole('dialog', { name: service.title, exact: true })
    await expect(bookingDialog).toBeVisible()
    const modalTimezone = bookingDialog.getByRole('button', { name: 'Time zone', exact: true })
    await expect(modalTimezone).toContainText('(America/New_York)')
    await expect(bookingDialog.getByRole('button', { name: /10:00 AM/ }).first()).toBeVisible()
    await page.setViewportSize({ width: 390, height: 844 })
    await modalTimezone.click()
    await expect(timezonePopup).toBeVisible()
    const mobilePopupBox = await timezonePopup.boundingBox()
    expect(mobilePopupBox!.height).toBeLessThanOrEqual(241)
    expect(mobilePopupBox!.x).toBeGreaterThanOrEqual(0)
    expect(mobilePopupBox!.x + mobilePopupBox!.width).toBeLessThanOrEqual(390)
    expect(mobilePopupBox!.y + mobilePopupBox!.height).toBeLessThanOrEqual(844)
    await zoneSearch.fill('Pacific/Auckland')
    await expect(timezonePopup.getByRole('option')).toHaveCount(1)
    await zoneSearch.press('Escape')
    await expect(timezonePopup).toBeHidden()
    await expect(bookingDialog).toBeVisible()
    await expect(modalTimezone).toBeFocused()
    await modalTimezone.click()
    await zoneSearch.fill('UTC')
    await expect(timezonePopup.getByRole('option')).toHaveCount(1)
    await zoneSearch.press('ArrowDown')
    await zoneSearch.press('Enter')
    await expect(modalTimezone).toContainText('(UTC)')
    await expect(bookingDialog.getByRole('button', { name: /2:00 PM/ }).first()).toBeVisible()
    await expect(bookingDialog.getByText('Party size', { exact: true })).toHaveCount(0)
    await expect(bookingDialog.getByRole('button', { name: /more guests|fewer guests/i })).toHaveCount(0)
    await bookingDialog.getByRole('button', { name: /2:00 PM/ }).first().click()
    await page.setViewportSize({ width: 1280, height: 720 })
    await page.setViewportSize({ width: 390, height: 844 })
    const sessions = await Promise.all(products.map(async product => {
      const response = await request.get(`/api/public/products/${product.slug}/sessions?location_id=online&from=${day}&to=${day}`, { headers })
      expect(response.status(), await response.text()).toBe(200)
      return (await response.json()).sessions.find((session: { starts_at: string }) => session.starts_at.startsWith(day))
    }))
    const book = (index: number) => request.post(`/api/public/products/${products[index]!.slug}/book`, { headers, data: { session_id: sessions[index].id, variant_id: products[index]!.variants[0]!.id, party_size: 1, guest_name: `Local review ${index}`, guest_email: `consultation-${stamp}-${index}@playwright.example` } })
    const results = await Promise.all([book(0), book(1)])
    expect(results.map(result => result.status()).sort()).toEqual([201, 409])
    const pending = await results.find(result => result.status() === 201)!.json()
    expect(pending).toMatchObject({ status: 'pending', booking_id: pending.request_id })
    expect(pending.operational_booking_id).not.toBe(pending.request_id)
    expect(pending.policy_summary.additional_notes_html).toBe('Contact us at least one day before your appointment to cancel.')
    const details = await page.request.get(`/api/dashboard/bookings/booking/${pending.request_id}?org=north-carolina-legal-services`)
    expect(details.status(), await details.text()).toBe(200)
    expect((await details.json()).booking).toMatchObject({ locationId: null, locationTitle: 'Online', status: 'pending', operationalBookingId: pending.operational_booking_id })
    const key = `reject-${stamp}`
    for (let replay = 0; replay < 2; replay++) {
      const reject = await page.request.post(`/api/dashboard/organizations/${org}/guest-threads/${pending.request_id}/operations/reject`, { data: { idempotencyKey: key } })
      expect(reject.status(), await reject.text()).toBe(200)
    }
    const remaining = await request.get(`/api/public/products/${products[0]!.slug}/sessions?location_id=online&from=${day}&to=${day}`, { headers })
    expect((await remaining.json()).sessions.find((session: { id: string }) => session.id === sessions[0].id)).toMatchObject({ remaining: 1, is_full: false })
    const dialog = bookingDialog
    await dialog.getByRole('button', { name: /2:00 PM/ }).first().click()
    await dialog.getByRole('button', { name: 'Continue', exact: true }).click()
    await expect(dialog.getByText(/ · 2:00 PM$/, { exact: false })).toBeVisible()
    await dialog.getByLabel('Full name', { exact: true }).fill('Browser review guest')
    await dialog.getByLabel('Email address', { exact: true }).fill(`browser-consultation-${stamp}@playwright.example`)
    const submitted = page.waitForResponse(response => response.url().includes(`/products/${products[0]!.slug}/book`) && response.request().method() === 'POST')
    await dialog.getByRole('button', { name: 'Request appointment', exact: true }).click()
    const browserBookingResponse = await submitted
    expect(browserBookingResponse.status(), await browserBookingResponse.text()).toBe(201)
    const browserBooking = await browserBookingResponse.json()
    expect(browserBooking.status).toBe('pending')
    await expect(page).toHaveURL(/\/bookings\/confirmed/)
    await expect(page.getByRole('heading', { name: /Request received, Browser review guest/ })).toBeVisible()
    expect(analyticsFailures).toEqual([])
    for (let replay = 0; replay < 2; replay++) {
      const confirm = await page.request.post(`/api/dashboard/organizations/${org}/guest-threads/${browserBooking.request_id}/operations/confirm`, { data: { idempotencyKey: `confirm-${stamp}` } })
      expect(confirm.status(), await confirm.text()).toBe(200)
    }
    const confirmedDetails = await page.request.get(`/api/dashboard/bookings/booking/${browserBooking.request_id}?org=north-carolina-legal-services`)
    expect((await confirmedDetails.json()).booking).toMatchObject({ status: 'confirmed', operationalBookingId: browserBooking.operational_booking_id })
    for (const mode of ['external_url', 'native_disabled', 'native'] as const) {
      const switchMode = await page.request.put(`${editor}/consultation`, { data: { mode } })
      expect(switchMode.status(), await switchMode.text()).toBe(200)
      const publicDocument = await request.get('/api/public/blawby/document?recipe=schedule', { headers })
      expect(publicDocument.status(), await publicDocument.text()).toBe(200)
      expect((await publicDocument.json()).shell.consultation.mode).toBe(mode)
      await page.goto(service.path)
      await expect(page.locator('[data-media-gallery]')).toHaveCount(mode === 'native' ? 1 : 0)
      await expect(page.locator('[data-block-type="hero"]')).toHaveCount(mode === 'native' ? 0 : 1)
      await page.goto('/schedule')
      await expect(page.getByRole('combobox', { name: 'Service', exact: true })).toHaveCount(mode === 'native' ? 1 : 0)
      if (mode === 'external_url') await expect(page.locator('[data-parity-section="schedule-hero"] a')).toHaveAttribute('href', previous.external_url)
      const binding = (await (await page.request.get(`${editor}/pages/${service.id}`)).json()).page
      expect(binding.product_id).toBe(products[0]!.id)
      expect(content(binding.blocks)).toEqual(content(service.blocks))
      const retained = await page.request.get(`/api/dashboard/bookings/booking/${browserBooking.request_id}?org=north-carolina-legal-services`)
      expect((await retained.json()).booking).toMatchObject({ status: 'confirmed', operationalBookingId: browserBooking.operational_booking_id })
    }
    await bindViaMcp(null)
    await page.goto(service.path)
    await expect(page.locator('[data-media-gallery]')).toHaveCount(0)
    await expect(page.locator('[data-block-type="hero"]')).toHaveCount(1)
    await bindViaMcp(products[0]!.id)
    await page.goto(service.path)
    await expect(page.locator('[data-media-gallery]')).toHaveCount(1)
    const browserCancel = await request.post(`/api/public/booking-requests/${browserBooking.request_id}/cancel`, { headers: { ...headers, authorization: `Bearer ${browserBooking.cancellation_token}` } })
    expect(browserCancel.status(), await browserCancel.text()).toBe(200)
    const cancelledBrowserDetails = await page.request.get(`/api/dashboard/bookings/booking/${browserBooking.request_id}?org=north-carolina-legal-services`)
    expect((await cancelledBrowserDetails.json()).booking.status).toBe('cancelled')
    const paid = await page.request.patch(`${editor}/products/${products[0]!.id}`, { data: { variants: [{ id: products[0]!.variants[0]!.id, name: 'Online', prices: [{ unit_amount: 7500, currency: 'USD' }] }] } })
    expect(paid.status(), await paid.text()).toBe(200)
    const blocked = await book(0)
    expect(blocked.status(), await blocked.text()).toBe(409)
    expect(await blocked.json()).toMatchObject({ code: 'payment_required' })
    const instantPolicy = await page.request.put(`${editor}/products/${products[0]!.id}/booking`, { data: { duration_minutes: 45, default_capacity: 1, confirmation_mode: 'instant', online_payment_required: false } })
    expect(instantPolicy.status(), await instantPolicy.text()).toBe(200)
    const instantResponse = await book(0)
    expect(instantResponse.status(), await instantResponse.text()).toBe(201)
    const instant = await instantResponse.json()
    expect(instant.status).toBe('confirmed')
    for (let replay = 0; replay < 2; replay++) {
      const cancel = await request.post(`/api/public/booking-requests/${instant.request_id}/cancel`, { headers: { ...headers, authorization: `Bearer ${instant.cancellation_token}` } })
      expect(cancel.status(), await cancel.text()).toBe(replay === 0 ? 200 : 404)
      const cancelledDetails = await page.request.get(`/api/dashboard/bookings/booking/${instant.request_id}?org=north-carolina-legal-services`)
      expect((await cancelledDetails.json()).booking.status).toBe('cancelled')
      const released = await request.get(`/api/public/products/${products[0]!.slug}/sessions?location_id=online`, { headers })
      expect((await released.json()).sessions.find((session: { id: string }) => session.id === sessions[0].id).remaining).toBe(1)
    }
  } finally {
    await writeBinding(cleanupRequest, service.product_id ?? null)
    const restoredMode = await cleanupRequest.put(`${editor}/consultation`, { data: { mode: previous.mode } })
    expect(restoredMode.status(), await restoredMode.text()).toBe(200)
    const restoredSettings = await cleanupRequest.get(`${editor}/consultation`)
    expect(restoredSettings.status()).toBe(200)
    expect((await restoredSettings.json()).mode).toBe(previous.mode)
    for (const product of products) {
      const unpublished = await cleanupRequest.put(`${editor}/products/${product.id}/publication`, { data: { published: false } })
      expect(unpublished.status(), await unpublished.text()).toBe(200)
      const publication = await cleanupRequest.get(`${editor}/products/${product.id}`)
      expect(publication.status()).toBe(200)
      expect((await publication.json()).product.publications).toContainEqual({ organization_id: org, published: false })
      const deleted = await cleanupRequest.delete(`${editor}/products/${product.id}`)
      if (deleted.status() === 200) continue
      // Canonical Product deletion preserves booked history, even when cancelled.
      expect(deleted.status(), await deleted.text()).toBe(409)
      const archivedBooking = await cleanupRequest.put(`${editor}/products/${product.id}/booking`, { data: { duration_minutes: 45, default_capacity: 1, calendar_group: null } })
      expect(archivedBooking.status(), await archivedBooking.text()).toBe(200)
      const removedSchedule = await cleanupRequest.put(`${editor}/products/${product.id}/availability`, { data: { location_id: null, slots: [] } })
      expect(removedSchedule.status(), await removedSchedule.text()).toBe(200)
      const deactivated = await cleanupRequest.patch(`${editor}/products/${product.id}`, { data: { active: false } })
      expect(deactivated.status(), await deactivated.text()).toBe(200)
      const archived = await cleanupRequest.get(`${editor}/products/${product.id}`)
      expect(archived.status()).toBe(200)
      expect((await archived.json()).product).toMatchObject({ active: false, booking: { calendar_group: null } })
      const availability = await cleanupRequest.get(`${editor}/products/${product.id}/availability?location_id=online`)
      expect(availability.status()).toBe(200)
      expect((await availability.json()).rules).toEqual([])
    }
    await cleanupRequest.dispose()
  }
})
