import {expect,test} from '@playwright/test'
import {authRequestHeaders} from './helpers/auth'
const password='Payments-Local-Proof-2026!Aa'
test.use({ignoreHTTPSErrors:true})
test('account cancellation owns the visit, retains principal and offers exact merchant contacts',async({page,browser,baseURL})=>{
 test.setTimeout(90000)
 test.skip(process.env.PAYMENTS_BUYER_PROOF!=='true'||!['localhost','127.0.0.1'].includes(new URL(baseURL!).hostname),'Explicit local-only buyer fixture; never provider proof')
 const recovery=process.env.PAYMENTS_BUYER_RECOVERY==='true'
 const origin=new URL(baseURL!).origin,headers=authRequestHeaders(baseURL!)
 const login=await page.request.post('/api/auth/sign-in/email',{headers,data:{email:'payments-proof-owner@playwright.example',password}})
 expect(login.status(),await login.text()).toBe(200)
 const before=await (await page.request.get('/api/account')).json()
 expect(before.bookings.find((v:{id:string})=>v.id==='payments-buyer-booking')).toMatchObject({status:recovery?'cancelled':'confirmed',can_cancel:!recovery,contactEmail:'business@playwright.example'})
 const outsider=await browser.newContext({baseURL,ignoreHTTPSErrors:true})
 try{
  const signed=await outsider.request.post('/api/auth/sign-in/email',{headers,data:{email:'payments-proof-buyer@playwright.example',password}})
  expect(signed.status(),await signed.text()).toBe(200)
  const denied=await outsider.request.post('/api/account/cancel',{headers:{origin},data:{request_id:'payments-buyer-request'}})
  expect(denied.status()).toBe(404)
  const account=await (await outsider.request.get('/api/account')).json()
  expect(account.bookings).toEqual([]);expect(account.reservations).toEqual([])
 }finally{await outsider.close()}
 const csrf=await page.request.post('/api/account/cancel',{data:{request_id:'payments-buyer-request'}})
 expect(csrf.status()).toBe(403)
 const ended=await page.request.post('/api/account/cancel',{headers:{origin},data:{request_id:'payments-buyer-ended-request'}})
 expect(ended.status()).toBe(409)
 await page.goto('/account')
 const booking=page.getByTestId('buyer-visit-payments-buyer-booking'),reservation=page.getByTestId('buyer-visit-payments-buyer-reservation')
 if(!recovery)await expect(booking.getByRole('link',{name:'Request a change by email'})).toHaveAttribute('href','mailto:business@playwright.example?subject=Change%20request%20payments-buyer-request')
 await expect(reservation.getByRole('link',{name:'Request a change by email'})).toHaveAttribute('href','mailto:branch@playwright.example?subject=Change%20request%20payments-buyer-reservation-request')
 await expect(page.getByTestId('buyer-visit-payments-buyer-ended-booking').getByRole('button',{name:'Cancel booking',exact:true})).toHaveCount(0)
 if(!recovery){
 await booking.getByRole('button',{name:'Cancel booking',exact:true}).click()
 await expect(booking.getByText('Cancel this booking? Cancellation does not automatically refund a payment.')).toBeVisible()
 const cancelled=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/account/cancel'&&r.request().method()==='POST')
 await booking.getByRole('button',{name:'Confirm cancellation',exact:true}).click()
 expect((await cancelled).status()).toBe(200)
 }
 await expect(booking.getByText('Buyer proof consultation · cancelled',{exact:true})).toBeVisible()
 await expect(booking.getByRole('link',{name:'Contact the business by email'})).toBeVisible()
 const replay=await page.request.post('/api/account/cancel',{headers:{origin},data:{request_id:'payments-buyer-request'}})
 expect(replay.status(),await replay.text()).toBe(200)
 await reservation.getByRole('button',{name:'Cancel reservation',exact:true}).click()
 await reservation.getByRole('button',{name:'Confirm cancellation',exact:true}).click()
 await expect(reservation.getByText('Reservation · cancelled',{exact:true})).toBeVisible()
 const after=await (await page.request.get('/api/account')).json()
 expect(after.payments.find((p:{id:string})=>p.id==='payments-buyer-payment')).toMatchObject({captured_amount:10000,refunded_amount:0,state:'captured'})
 expect(after.refunds.filter((r:{payment_id:string})=>r.payment_id==='payments-buyer-payment')).toEqual([])
 expect(after.bookings.find((v:{id:string})=>v.id==='payments-buyer-booking')).toMatchObject({status:'cancelled',can_cancel:false})
 expect(after.reservations.find((v:{id:string})=>v.id==='payments-buyer-reservation')).toMatchObject({status:'cancelled',can_cancel:false})
 await page.screenshot({path:'artifacts/payments-buyer-management.png',fullPage:true})
})

test('account final snapshot renders the application stylesheet and persisted cancellations',async({page,baseURL})=>{
 test.skip(process.env.PAYMENTS_BUYER_PROOF!=='true'||!['localhost','127.0.0.1'].includes(new URL(baseURL!).hostname),'Explicit local-only readback of the exercised fixture')
 const login=await page.request.post('/api/auth/sign-in/email',{headers:authRequestHeaders(baseURL!),data:{email:'payments-proof-owner@playwright.example',password}})
 expect(login.status(),await login.text()).toBe(200)
 await page.goto('/account')
 await expect(page.locator('link[rel="stylesheet"][href="/_nuxt/surfaces/platform-app.css"]')).toHaveCount(1)
 const booking=page.getByTestId('buyer-visit-payments-buyer-booking'),reservation=page.getByTestId('buyer-visit-payments-buyer-reservation')
 await expect(booking.getByText('Buyer proof consultation · cancelled',{exact:true})).toBeVisible()
 await expect(reservation.getByText('Reservation · cancelled',{exact:true})).toBeVisible()
 await expect(booking.getByRole('button',{name:'Cancel booking',exact:true})).toHaveCount(0)
 await expect(booking.getByRole('link',{name:'Contact the business by email'})).toHaveAttribute('href','mailto:business@playwright.example?subject=Booking%20payments-buyer-request')
 await expect(page.getByRole('heading',{name:'Your account',exact:true})).toHaveCSS('font-weight','600')
 const state=await (await page.request.get('/api/account')).json()
 expect(state.payments.find((p:{id:string})=>p.id==='payments-buyer-payment')).toMatchObject({state:'captured',captured_amount:10000,refunded_amount:0})
 await page.screenshot({path:'artifacts/payments-buyer-management.png',fullPage:true})
})
