import {expect,test} from '@playwright/test'
import Stripe from 'stripe'
import {authRequestHeaders} from './helpers/auth'
import {mcpRequest} from './helpers/mcp'
const password='Payments-Local-Proof-2026!Aa'
test('local Worker financial servicing, buyer ownership and signed payment ingress',async({page,request,baseURL,browser})=>{
 test.skip(process.env.PAYMENTS_LOCAL_PROOF!=='true'||!['localhost','127.0.0.1'].includes(new URL(baseURL!).hostname),'Explicit synthetic fixtures in isolated checkout; never provider-payment proof')
 const origin=new URL(baseURL!).origin,authHeaders=authRequestHeaders(baseURL!)
 const signin=await page.request.post('/api/auth/sign-in/email',{headers:authHeaders,data:{email:'payments-proof-owner@playwright.example',password}})
 expect(signin.status(),await signin.text()).toBe(200)
 // Real CMS/read API boundary with deliberately unconfigured provider credentials:
 // this proves visible setup failure, never successful native onboarding.
 const connect=await page.request.get('/api/dashboard/connect?org=payments-local-proof')
 expect(connect.status(),await connect.text()).toBe(200)
 expect(await connect.json()).toMatchObject({success:true,account:null})
 await page.goto('/dashboard/payments-local-proof/settings/integrations/stripe')
 await expect(page.getByRole('heading',{name:'Stripe',exact:true})).toBeVisible()
 await expect(page.getByText('Stripe Connect is unavailable',{exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'Continue to Stripe',exact:true})).toBeDisabled()
 await page.screenshot({path:'artifacts/payments-cms-onboarding-unconfigured.png',fullPage:true})
 const api='/api/dashboard/payments?org=payments-local-proof'
 const transactions=await page.request.get(api)
 expect(transactions.status(),await transactions.text()).toBe(200)
 expect((await transactions.json()).payments.some((p:{id:string})=>p.id==='payments-proof-order')).toBe(true)
 await page.goto('/dashboard/payments-local-proof/payments/transactions/payments-proof-order')
 await expect(page.getByRole('heading',{name:'Transaction',exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'Immutable physical order',exact:true})).toBeVisible()
 await page.screenshot({path:'artifacts/payments-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'artifacts/payments-mobile.png',fullPage:true})
 const fulfill=page.getByRole('button',{name:'Mark fulfilled',exact:true})
 await expect(fulfill).toBeVisible()
 await fulfill.click()
 await expect(page.getByRole('heading',{name:'Order · fulfilled',exact:true})).toBeVisible()
 // Fulfillment never changes captured/refunded principal.
 const after=await (await page.request.get(`${api}&payment_id=payments-proof-order`)).json()
 expect(after.order.fulfillment_status).toBe('fulfilled')
 expect(after.payment).toMatchObject({captured_amount:10000,refunded_amount:0})
 const newCheckout=await page.request.post('/api/dashboard/payments/checkout?org=payments-local-proof',{headers:{origin},data:{product_id:'archived-product',variant_id:'archived-variant',quantity:1,idempotency_key:crypto.randomUUID()}})
 expect(newCheckout.status()).toBe(403)
 const stillOwned=await (await page.request.get(api)).json()
 expect(stillOwned.payments).toHaveLength(2)
 const reject=await mcpRequest(page.request,baseURL!,{method:'tools/call',toolName:'reject_product_booking',args:{organization_id:'payments-proof-org',operational_booking_id:'payments-proof-review-booking',idempotency_key:crypto.randomUUID()}})
 expect(reject.status(),await reject.text()).toBe(200)
 const result=(await reject.json()).result
 expect(result.isError).toBe(true)
 expect(result.structuredContent).toMatchObject({success:false,operation_completed:false,confirmation_required:true,code:'financial_approval_required'})
 const approvalUrl=new URL(result.structuredContent.financial_approval_url)
 expect(approvalUrl.origin).toBe(origin)
 expect(approvalUrl.pathname).toBe('/dashboard/payments-local-proof/payments/refunds/approve')
 const pending=await page.request.get('/api/dashboard/bookings/booking/payments-proof-review-request?org=payments-local-proof')
 expect(pending.status(),await pending.text()).toBe(200)
 expect((await pending.json()).booking.status).toBe('pending')
 const principal=await (await page.request.get(`${api}&payment_id=payments-proof-review`)).json()
 expect(principal.payment).toMatchObject({captured_amount:10000,refunded_amount:0})
 await page.goto(approvalUrl.toString())
 await expect(page.getByRole('button',{name:/Approve/})).toBeVisible()
 const noOrigin=await page.request.post('/api/dashboard/payments/refund?org=payments-local-proof',{data:{action:'prepare',payment_id:'payments-proof-order',amount:100}})
 expect(noOrigin.status()).toBe(403)
 const prepared=await page.request.post('/api/dashboard/payments/refund?org=payments-local-proof',{headers:{origin},data:{action:'prepare',payment_id:'payments-proof-order',amount:100}})
 expect(prepared.status(),await prepared.text()).toBe(200)
 const authorization=await prepared.json()
 await page.goto(`/dashboard/payments-local-proof/payments/refunds/approve?id=${authorization.authorization_id}`)
 await expect(page.getByRole('button',{name:/Approve/})).toBeVisible()
 const ownerAccount=await (await page.request.get('/api/account')).json()
 expect(ownerAccount.payments.map((payment:{id:string})=>payment.id)).toEqual(['payments-proof-order'])
 await page.goto('/account')
 await expect(page.getByText('Immutable physical order',{exact:true})).toBeVisible()
 const buyer=await browser.newContext({baseURL})
 try{
 const login=await buyer.request.post('/api/auth/sign-in/email',{headers:authHeaders,data:{email:'payments-proof-buyer@playwright.example',password}})
 expect(login.status(),await login.text()).toBe(200)
 const blocked=await buyer.request.get(`${api}&payment_id=payments-proof-order`)
 expect(blocked.status()).toBe(404)
 const own=await (await buyer.request.get('/api/account')).json()
 expect(own.payments).toEqual([])
 }finally{await buyer.close()}
 const stripe=new Stripe('sk_test_local_signature_only')
 const payload=JSON.stringify({id:'evt_local_signature',object:'event',type:'customer.created',account:'acct_local_fixture',livemode:false,data:{object:{id:'cus_ignored'}}})
 const secret='whsec_local_payments_boundary',signature=stripe.webhooks.generateTestHeaderString({payload,secret})
 const unsigned=await request.post('/api/stripe/payments/webhook',{data:payload,headers:{'content-type':'application/json'}})
 expect(unsigned.status()).toBe(400)
 const tampered=await request.post('/api/stripe/payments/webhook',{data:payload+' ',headers:{'content-type':'application/json','stripe-signature':signature}})
 expect(tampered.status()).toBe(400)
 for(let replay=0;replay<2;replay++){
 const signed=await request.post('/api/stripe/payments/webhook',{data:payload,headers:{'content-type':'application/json','stripe-signature':signature}})
 expect(signed.status(),await signed.text()).toBe(200)
 expect(await signed.json()).toMatchObject({received:true})
 }
 const forged=await request.post('/api/account/checkout-return',{data:{payment_id:'payments-proof-order',purchase_claim:'forged-return'}})
 expect(forged.status()).toBe(400)
})

test.describe('existing native sandbox CMS account',()=>{
 test.use({ignoreHTTPSErrors:true})
 test('incomplete Stripe return refreshes native requirements without granting readiness',async({page,baseURL})=>{
  test.skip(process.env.PAYMENTS_CONNECT_READ_PROOF!=='true'||!['localhost','127.0.0.1'].includes(new URL(baseURL!).hostname),'Explicit read-only existing sandbox proof; never create or complete provider accounts here')
  await page.setViewportSize({width:1280,height:1000})
  const expectedAccount=process.env.PAYMENTS_CONNECT_READ_ACCOUNT
  expect(expectedAccount).toMatch(/^acct_/)
  const signin=await page.request.post('/api/auth/sign-in/email',{headers:authRequestHeaders(baseURL!),data:{email:'payments-proof-owner@playwright.example',password}})
  expect(signin.status(),await signin.text()).toBe(200)
  const endpoint='/api/dashboard/connect?org=payments-local-proof'
  const before=await page.request.get(endpoint)
  expect(before.status(),await before.text()).toBe(200)
  const original=(await before.json()).account
  expect(original).toMatchObject({stripeAccountId:expectedAccount,livemode:false,status:'action_required',cardPaymentsStatus:'restricted'})
  expect(original.requirements.length).toBeGreaterThan(0)
  const refresh=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/dashboard/connect/status'&&response.request().method()==='POST')
  await page.goto('/dashboard/payments-local-proof/settings/integrations/stripe?stripe_connect=returned')
  expect((await refresh).status()).toBe(200)
  await expect(page).not.toHaveURL(/stripe_connect=/)
  await expect(page.getByText('Action required',{exact:true})).toBeVisible()
  await expect(page.getByText('Stripe requirements',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Continue Stripe onboarding',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Refresh status',exact:true})).toBeVisible()
  const after=(await (await page.request.get(endpoint)).json()).account
  expect(after).toMatchObject({stripeAccountId:expectedAccount,livemode:false,status:'action_required',cardPaymentsStatus:'restricted'})
  expect(Date.parse(after.stripeRefreshedAt)).toBeGreaterThan(Date.parse(original.stripeRefreshedAt))
  await page.screenshot({path:'artifacts/payments-cms-onboarding-requirements.png',fullPage:true})
  await page.goto('/dashboard/payments-local-proof/settings/integrations')
  for(const path of ['/platform/integrations/stripe-blurple.svg','/platform/integrations/google-calendar.webp']){
   const image=page.locator(`img[src="${path}"]`)
   await expect(image).toBeVisible()
   await expect.poll(()=>image.evaluate(element=>(element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  }
  await page.screenshot({path:'artifacts/payments-integration-marks-light.png',fullPage:true})
  await page.evaluate(()=>document.documentElement.classList.add('dark'))
  await expect(page.locator('img[src="/platform/integrations/stripe-white.svg"]')).toBeVisible()
  await expect(page.locator('img[src="/platform/integrations/stripe-blurple.svg"]')).toBeHidden()
  await page.screenshot({path:'artifacts/payments-integration-marks-dark.png',fullPage:true})
 })
})
