DROP INDEX `idx_customers_stripe_customer_id`;--> statement-breakpoint
DROP INDEX `idx_review_requests_token_hash`;--> statement-breakpoint
CREATE INDEX `review_requests_organization_id_idx` ON `review_requests` (`organization_id`);--> statement-breakpoint
CREATE INDEX `account_userId_idx` ON `account` (`userId`);--> statement-breakpoint
CREATE INDEX `ai_usage_log_organization_id_idx` ON `ai_usage_log` (`organization_id`);--> statement-breakpoint
CREATE INDEX `blog_posts_org_site_idx` ON `blog_posts` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `booking_policies_organization_id_idx` ON `booking_policies` (`organization_id`);--> statement-breakpoint
CREATE INDEX `chowbot_channel_state_user_id_idx` ON `chowbot_channel_state` (`user_id`);--> statement-breakpoint
CREATE INDEX `chowbot_conversations_org_site_idx` ON `chowbot_conversations` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `chowbot_conversations_user_id_idx` ON `chowbot_conversations` (`user_id`);--> statement-breakpoint
CREATE INDEX `chowbot_messages_conversation_id_idx` ON `chowbot_messages` (`conversation_id`);--> statement-breakpoint
CREATE INDEX `chowbot_messages_org_site_idx` ON `chowbot_messages` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `contact_submissions_org_site_idx` ON `contact_submissions` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `experience_bookings_organization_id_idx` ON `experience_bookings` (`organization_id`);--> statement-breakpoint
CREATE INDEX `experience_slot_overrides_org_site_idx` ON `experience_slot_overrides` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `experiences_org_site_idx` ON `experiences` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `guest_threads_organization_id_idx` ON `guest_threads` (`organization_id`);--> statement-breakpoint
CREATE INDEX `invitation_organizationId_idx` ON `invitation` (`organizationId`);--> statement-breakpoint
CREATE INDEX `location_qa_organization_id_idx` ON `location_qa` (`organization_id`);--> statement-breakpoint
CREATE INDEX `member_userId_organizationId_idx` ON `member` (`userId`,`organizationId`);--> statement-breakpoint
CREATE INDEX `member_organizationId_idx` ON `member` (`organizationId`);--> statement-breakpoint
CREATE INDEX `menu_item_translations_menu_item_id_idx` ON `menu_item_translations` (`menu_item_id`);--> statement-breakpoint
CREATE INDEX `menu_items_menu_id_idx` ON `menu_items` (`menu_id`);--> statement-breakpoint
CREATE INDEX `menu_translations_menu_id_idx` ON `menu_translations` (`menu_id`);--> statement-breakpoint
CREATE INDEX `menus_organization_id_site_id_idx` ON `menus` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `notification_events_org_site_idx` ON `notification_events` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `onboarding_drafts_user_id_idx` ON `onboarding_drafts` (`user_id`);--> statement-breakpoint
CREATE INDEX `post_channel_jobs_post_id_idx` ON `post_channel_jobs` (`post_id`);--> statement-breakpoint
CREATE INDEX `post_media_org_site_idx` ON `post_media` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `post_translations_post_id_idx` ON `post_translations` (`post_id`);--> statement-breakpoint
CREATE INDEX `posts_org_site_idx` ON `posts` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `reservation_slot_overrides_org_site_idx` ON `reservation_slot_overrides` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `reservation_submissions_organization_id_idx` ON `reservation_submissions` (`organization_id`);--> statement-breakpoint
CREATE INDEX `reviews_organization_id_idx` ON `reviews` (`organization_id`);--> statement-breakpoint
CREATE INDEX `service_addon_purchases_organization_id_idx` ON `service_addon_purchases` (`organization_id`);--> statement-breakpoint
CREATE INDEX `session_userId_idx` ON `session` (`userId`);--> statement-breakpoint
CREATE INDEX `site_config_org_site_idx` ON `site_config` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `site_consultation_settings_organization_id_idx` ON `site_consultation_settings` (`organization_id`);--> statement-breakpoint
CREATE INDEX `site_conversion_events_organization_id_idx` ON `site_conversion_events` (`organization_id`);--> statement-breakpoint
CREATE INDEX `site_domain_events_domain_id_idx` ON `site_domain_events` (`domain_id`);--> statement-breakpoint
CREATE INDEX `site_domains_org_site_idx` ON `site_domains` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `site_entitlements_organization_id_idx` ON `site_entitlements` (`organization_id`);--> statement-breakpoint
CREATE INDEX `site_events_org_site_idx` ON `site_events` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `site_pageview_events_site_created_idx` ON `site_pageview_events` (`site_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `site_theme_tokens_organization_id_idx` ON `site_theme_tokens` (`organization_id`);--> statement-breakpoint
CREATE INDEX `site_transfer_requests_site_id_idx` ON `site_transfer_requests` (`site_id`);--> statement-breakpoint
CREATE INDEX `sites_organization_id_idx` ON `sites` (`organization_id`);--> statement-breakpoint
CREATE INDEX `submission_messages_org_site_idx` ON `submission_messages` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `tenant_navigation_items_organization_id_idx` ON `tenant_navigation_items` (`organization_id`);--> statement-breakpoint
CREATE INDEX `tenant_redirects_organization_id_idx` ON `tenant_redirects` (`organization_id`);--> statement-breakpoint
CREATE INDEX `translation_job_items_job_id_idx` ON `translation_job_items` (`job_id`);--> statement-breakpoint
CREATE INDEX `translation_job_items_org_site_idx` ON `translation_job_items` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `translation_jobs_org_site_idx` ON `translation_jobs` (`organization_id`,`site_id`);--> statement-breakpoint
CREATE INDEX `work_requests_organization_id_idx` ON `work_requests` (`organization_id`);