import type { McpToolDefinition } from './shared'
import { BLOG_NAV_FIELDS_SCHEMA, ROBOTS_DIRECTIVE_ENUM, blogComponentInputSchema, blogPostMutationResultObject, blogPostObject, siteTool } from './shared'

export const BLOG_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'list_blog_posts',
      description: 'List this site\'s blog posts (draft and published). This is the site\'s own long-form content blog — distinct from list_posts, which is the social-update feed (events/offers/announcements that fan out to Facebook/Instagram/GMB).',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { status: { type: 'string', enum: ['draft', 'published'] } },
      outputSchema: {
        type: 'object',
        properties: { posts: { type: 'array', items: blogPostObject } },
        required: ['posts'],
      },
    }),
  siteTool({
      name: 'get_blog_post',
      description: 'Get a single blog post by id or slug.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { post_id: { type: 'string', description: 'Post id or slug.' } },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post: blogPostObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'create_blog_post',
      description: 'Create a blog post for this site. Set publish=true to publish immediately, or omit/false to save as a draft. category is free text for tenant blogs (no fixed taxonomy). Use this for long-form narrative/story content, not a time-boxed announcement (use create_post for that) or a permanent bookable offering with its own pricing/availability page (use create_experience for that instead).',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        title: { type: 'string' },
        body: { type: 'string', description: 'Use {{component type="faq"}} or {{component type="how_to"}} in the body when you want structured embeds.' },
        excerpt: { type: 'string' },
        category: { type: 'string' },
        tags: { type: 'array', items: { type: 'string' }, description: 'Searchable topical tags. Use a short, deduplicated list; category remains the primary public grouping.' },
        components: {
          type: 'array',
          description: 'Optional structured content components: faq, how_to, or ai_assistance. FAQ: data.items[] of { question, answer, position? }. How-To: data.steps[] of { name, text, image_asset_id?, url?, position? }. AI assistance: data.prompts[] with prompt plus optional title/description/copy_label; keep schema_enabled=false because it has no schema.org representation.',
          items: blogComponentInputSchema,
        },
        ...BLOG_NAV_FIELDS_SCHEMA,
        seo_title: { type: ['string', 'null'], description: 'Optional SEO/browser-tab title override. Falls back to the post title if unset.' },
        seo_description: { type: 'string' },
        seo_keywords: { type: 'string' },
        canonical_url: { type: 'string' },
        robots: { type: ['string', 'null'], enum: [...ROBOTS_DIRECTIVE_ENUM, null] },
        publish: { type: 'boolean', description: 'Publish immediately. Defaults to false (draft).' },
      },
      required: ['title', 'body'],
      outputSchema: blogPostMutationResultObject,
    }),
  siteTool({
      name: 'update_blog_post',
      description: 'Update a blog post. Only provided fields are changed. Set publish=true to publish, or unpublish=true to revert to draft.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        post_id: { type: 'string', description: 'Post id or slug.' },
        title: { type: 'string' },
        body: { type: 'string', description: 'Use {{component type="faq"}} or {{component type="how_to"}} in the body when you want structured embeds.' },
        excerpt: { type: 'string' },
        category: { type: 'string' },
        tags: { type: 'array', items: { type: 'string' }, description: 'Searchable topical tags. Use a short, deduplicated list; category remains the primary public grouping.' },
        components: {
          type: 'array',
          description: 'Updated structured content components: faq, how_to, or ai_assistance. Sending components replaces the complete set; omit it to preserve existing components. Keep schema_enabled=false for ai_assistance.',
          items: blogComponentInputSchema,
        },
        ...BLOG_NAV_FIELDS_SCHEMA,
        seo_title: { type: ['string', 'null'], description: 'Optional SEO/browser-tab title override. Falls back to the post title if unset.' },
        seo_description: { type: 'string' },
        seo_keywords: { type: 'string' },
        canonical_url: { type: 'string' },
        robots: { type: ['string', 'null'], enum: [...ROBOTS_DIRECTIVE_ENUM, null] },
        publish: { type: 'boolean' },
        unpublish: { type: 'boolean' },
      },
      required: ['post_id'],
      outputSchema: blogPostMutationResultObject,
    }),
  siteTool({
      name: 'publish_blog_post',
      description: 'Publish a tenant blog post immediately. Use only after the writer has approved the final article.',
      domain: 'blog', minimumRole: 'editor', confirmRequired: false,
      inputSchema: { post_id: { type: 'string', description: 'Post id or slug.' } }, required: ['post_id'],
      outputSchema: blogPostMutationResultObject,
    }),
  siteTool({
      name: 'unpublish_blog_post',
      description: 'Move a published tenant blog post back to draft.',
      domain: 'blog', minimumRole: 'editor', confirmRequired: false,
      inputSchema: { post_id: { type: 'string', description: 'Post id or slug.' } }, required: ['post_id'],
      outputSchema: blogPostMutationResultObject,
    }),
  siteTool({
      name: 'set_blog_post_image',
      description: 'Assign a saved media asset as a blog post\'s featured image. Call get_site_media_assets first to find an active image asset id.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        post_id: { type: 'string', description: 'Post id or slug.' },
        asset_id: { type: 'string', description: 'Active image asset id from get_site_media_assets.' },
      },
      required: ['post_id', 'asset_id'],
      outputSchema: blogPostMutationResultObject,
    }),
  siteTool({
      name: 'reorder_blog_posts',
      description: 'Set editorial navigation (section, title, order, visibility) for this site\'s blog posts without changing their taxonomy category or public URL. Blog posts do not support nav_group subgrouping (docs-only feature) — only nav_section.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        items: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              post_id: { type: 'string', description: 'Post id or slug.' },
              nav_section: BLOG_NAV_FIELDS_SCHEMA.nav_section,
              nav_title: BLOG_NAV_FIELDS_SCHEMA.nav_title,
              nav_order: { type: 'number' },
              nav_section_order: BLOG_NAV_FIELDS_SCHEMA.nav_section_order,
              hide_from_nav: BLOG_NAV_FIELDS_SCHEMA.hide_from_nav,
            },
            required: ['post_id', 'nav_order'],
          },
        },
      },
      required: ['items'],
      outputSchema: {
        type: 'object',
        properties: { success: { type: 'boolean' }, posts: { type: 'array', items: blogPostObject } },
        required: ['success', 'posts'],
      },
    }),
  siteTool({
      name: 'delete_blog_post',
      description: 'Delete a blog post.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { post_id: { type: 'string', description: 'Post id or slug.' } },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post_id: { type: 'string' }, deleted: { type: 'boolean' } },
        required: ['post_id', 'deleted'],
      },
    }),
]
