import type { McpToolDefinition } from './shared'
import { blogPostObject, siteTool } from './shared'

export const BLOG_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'list_blog_posts',
      description: 'List this site\'s blog posts (draft and published). This is the site\'s own long-form content blog — distinct from list_posts, which is the social-update feed (events/offers/announcements that fan out to Facebook/Instagram/GMB).',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { status: { type: 'string', enum: ['draft', 'published'] } },
      outputSchema: {
        type: 'object',
        properties: { posts: { type: 'array', items: blogPostObject } },
        required: ['posts'],
      },
    }),
  siteTool({
      name: 'get_blog_post',
      description: 'Get a single blog post by id or slug.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { post_id: { type: 'string', description: 'Post id or slug.' } },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post: blogPostObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'create_blog_post',
      description: 'Create a blog post for this site. Set publish=true to publish immediately, or omit/false to save as a draft. category is free text for tenant blogs (no fixed taxonomy).',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        title: { type: 'string' },
        body: { type: 'string', description: 'Use {{component type="faq"}} or {{component type="how_to"}} in the body when you want structured embeds.' },
        excerpt: { type: 'string' },
        category: { type: 'string' },
        components: {
          type: 'array',
          description: 'Optional structured content components. Use faq or how_to components only.',
          items: {
            type: 'object',
            properties: {
              type: { type: 'string', enum: ['faq', 'how_to'] },
              label: { type: ['string', 'null'] },
              status: { type: ['string', 'null'], enum: ['active', 'inactive', null] },
              render_enabled: { type: ['boolean', 'null'] },
              schema_enabled: { type: ['boolean', 'null'] },
              position: { type: ['number', 'null'] },
              data: { type: 'object' },
            },
          },
        },
        seo_description: { type: 'string' },
        seo_keywords: { type: 'string' },
        canonical_url: { type: 'string' },
        robots: { type: 'string', enum: ['index,follow', 'noindex,follow', 'index,nofollow', 'noindex,nofollow'] },
        publish: { type: 'boolean', description: 'Publish immediately. Defaults to false (draft).' },
      },
      required: ['title', 'body'],
      outputSchema: {
        type: 'object',
        properties: { post: blogPostObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'update_blog_post',
      description: 'Update a blog post. Only provided fields are changed. Set publish=true to publish, or unpublish=true to revert to draft.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        post_id: { type: 'string', description: 'Post id or slug.' },
        title: { type: 'string' },
        body: { type: 'string', description: 'Use {{component type="faq"}} or {{component type="how_to"}} in the body when you want structured embeds.' },
        excerpt: { type: 'string' },
        category: { type: 'string' },
        components: {
          type: 'array',
          description: 'Updated structured content components. Use faq or how_to components only.',
          items: {
            type: 'object',
            properties: {
              type: { type: 'string', enum: ['faq', 'how_to'] },
              label: { type: ['string', 'null'] },
              status: { type: ['string', 'null'], enum: ['active', 'inactive', null] },
              render_enabled: { type: ['boolean', 'null'] },
              schema_enabled: { type: ['boolean', 'null'] },
              position: { type: ['number', 'null'] },
              data: { type: 'object' },
            },
          },
        },
        seo_description: { type: 'string' },
        seo_keywords: { type: 'string' },
        canonical_url: { type: 'string' },
        robots: { type: 'string', enum: ['index,follow', 'noindex,follow', 'index,nofollow', 'noindex,nofollow'] },
        publish: { type: 'boolean' },
        unpublish: { type: 'boolean' },
      },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post: blogPostObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'set_blog_post_image',
      description: 'Assign a saved media asset as a blog post\'s featured image. Call get_site_media_assets first to find an active image asset id.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        post_id: { type: 'string', description: 'Post id or slug.' },
        asset_id: { type: 'string', description: 'Active image asset id from get_site_media_assets.' },
      },
      required: ['post_id', 'asset_id'],
      outputSchema: {
        type: 'object',
        properties: { post: blogPostObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'delete_blog_post',
      description: 'Delete a blog post.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { post_id: { type: 'string', description: 'Post id or slug.' } },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post_id: { type: 'string' }, deleted: { type: 'boolean' } },
        required: ['post_id', 'deleted'],
      },
    }),
]
