import type { McpToolDefinition } from './shared'
import { BLOG_NAV_FIELDS_SCHEMA, ROBOTS_DIRECTIVE_ENUM, blogPostMutationResultObject, blogPostObject, siteTool } from './shared'

const blogContentBlockSchema = {
  type: 'object',
  properties: {
    id: { type: 'string' },
    type: { type: 'string', enum: ['heading', 'markdown', 'image', 'gallery', 'faq', 'how_to', 'divider', 'ai_assistance', 'cta', 'callout'] },
    level: { type: ['number', 'null'] },
    data: { type: 'object', description: 'Typed block payload. Markdown requires markdown plus editor_mode (rich for visual-editor-safe prose, source for tables/raw HTML). FAQ uses items; How-To uses steps; images retain asset_id, alt, caption, and resolved media metadata.' },
  },
  required: ['type', 'data'],
} as const

export const BLOG_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'list_blog_posts',
      description: 'List this site\'s blog posts (draft and published). This is the site\'s own long-form content blog — distinct from list_posts, which is the social-update feed (events/offers/announcements that fan out to Facebook/Instagram/GMB).',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { status: { type: 'string', enum: ['draft', 'published', 'scheduled'] } },
      outputSchema: {
        type: 'object',
        properties: { posts: { type: 'array', items: blogPostObject } },
        required: ['posts'],
      },
    }),
  siteTool({
      name: 'get_blog_post',
      description: 'Get a single blog post by id or slug.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { post_id: { type: 'string', description: 'Post id or slug.' } },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: {
          post: blogPostObject,
          expected_document_updated_at: { type: ['string', 'null'], description: 'Concurrency token required when update_blog_post replaces content_blocks.' },
        },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'create_blog_post',
      description: 'Create a long-form, evergreen, SEO-indexed article (site history, guides, "why choose us") as a draft by default. Always review the draft at edit_url in the tenant-themed editor. Set publish=true only when explicitly requested; scheduled_for schedules publication. category is free text for tenant blogs. For time-boxed, social-style announcements (tonight\'s event, a limited offer) that publish immediately and can fan out to Facebook/Instagram/GMB, use create_post instead.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        title: { type: 'string' },
        excerpt: { type: 'string' },
        category: { type: 'string' },
        tags: { type: 'array', items: { type: 'string' }, description: 'Searchable topical tags. Use a short, deduplicated list; category remains the primary public grouping.' },
        content_blocks: { type: 'array', description: 'Canonical ordered article blocks. This is the source of truth for FAQ, How-To, media, and other structured content.', items: blogContentBlockSchema },
        seo_title: { type: ['string', 'null'], description: 'Optional SEO/browser-tab title override. Falls back to the post title if unset.' },
        seo_description: { type: 'string' },
        canonical_url: { type: 'string' },
        robots: { type: ['string', 'null'], enum: [...ROBOTS_DIRECTIVE_ENUM, null] },
        visibility: { type: 'string', enum: ['public', 'unlisted'], description: 'Unlisted posts work by direct URL but are excluded from indexes, search, feeds, and sitemap.' },
        scheduled_for: { type: ['string', 'null'], description: 'ISO 8601 datetime with timezone. Publishes automatically when due.' },
        publish: { type: 'boolean', description: 'Publish immediately. Defaults to false (draft).' },
      },
      required: ['title', 'content_blocks'],
      strict: true,
      outputSchema: blogPostMutationResultObject,
    }),
  siteTool({
      name: 'update_blog_post',
      description: 'Update a blog post. Only provided fields are changed. Always review the draft at edit_url. Set publish=true to publish, or unpublish=true to revert to draft.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        post_id: { type: 'string', description: 'Post id or slug.' },
        title: { type: 'string' },
        excerpt: { type: 'string' },
        category: { type: 'string' },
        tags: { type: 'array', items: { type: 'string' }, description: 'Searchable topical tags. Use a short, deduplicated list; category remains the primary public grouping.' },
        content_blocks: { type: 'array', description: 'Canonical ordered article blocks. Sending this replaces the complete draft block snapshot.', items: blogContentBlockSchema },
        expected_document_updated_at: { type: 'string', description: 'Required with content_blocks. Use the token returned by get_blog_post; stale tokens are rejected with a conflict.' },
        seo_title: { type: ['string', 'null'], description: 'Optional SEO/browser-tab title override. Falls back to the post title if unset.' },
        seo_description: { type: 'string' },
        canonical_url: { type: 'string' },
        robots: { type: ['string', 'null'], enum: [...ROBOTS_DIRECTIVE_ENUM, null] },
        visibility: { type: 'string', enum: ['public', 'unlisted'] },
        scheduled_for: { type: ['string', 'null'], description: 'ISO 8601 datetime with timezone; null clears scheduling.' },
        slug: { type: ['string', 'null'], description: 'Manual URL slug override. Published slug changes preserve a permanent redirect by default.' },
        redirect_old_slug: { type: 'boolean', description: 'Defaults true after first publish.' },
        publish: { type: 'boolean' },
        unpublish: { type: 'boolean' },
      },
      required: ['post_id'],
      strict: true,
      outputSchema: blogPostMutationResultObject,
    }),
  siteTool({
      name: 'publish_blog_post',
      description: 'Publish a tenant blog post immediately. Use only after the writer has approved the final article.',
      domain: 'blog', minimumRole: 'editor', confirmRequired: false,
      inputSchema: { post_id: { type: 'string', description: 'Post id or slug.' } }, required: ['post_id'],
      outputSchema: blogPostMutationResultObject,
    }),
  siteTool({
      name: 'unpublish_blog_post',
      description: 'Move a published tenant blog post back to draft.',
      domain: 'blog', minimumRole: 'editor', confirmRequired: false,
      inputSchema: { post_id: { type: 'string', description: 'Post id or slug.' } }, required: ['post_id'],
      outputSchema: blogPostMutationResultObject,
    }),
  siteTool({
      name: 'set_blog_post_image',
      description: 'Assign a saved media asset as a blog post\'s featured image. Call get_site_media_assets first to find an active image asset id.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        post_id: { type: 'string', description: 'Post id or slug.' },
        asset_id: { type: 'string', description: 'Active image asset id from get_site_media_assets.' },
      },
      required: ['post_id', 'asset_id'],
      outputSchema: blogPostMutationResultObject,
    }),
  siteTool({
      name: 'reorder_blog_posts',
      description: 'Set editorial navigation (section, title, order, visibility) for this site\'s blog posts without changing their taxonomy category or public URL. Blog posts do not support nav_group subgrouping (docs-only feature) — only nav_section.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        items: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              post_id: { type: 'string', description: 'Post id or slug.' },
              nav_section: BLOG_NAV_FIELDS_SCHEMA.nav_section,
              nav_title: BLOG_NAV_FIELDS_SCHEMA.nav_title,
              nav_order: { type: 'number' },
              nav_section_order: BLOG_NAV_FIELDS_SCHEMA.nav_section_order,
              hide_from_nav: BLOG_NAV_FIELDS_SCHEMA.hide_from_nav,
            },
            required: ['post_id', 'nav_order'],
          },
        },
      },
      required: ['items'],
      outputSchema: {
        type: 'object',
        properties: { success: { type: 'boolean' }, posts: { type: 'array', items: blogPostObject } },
        required: ['success', 'posts'],
      },
    }),
  siteTool({
      name: 'delete_blog_post',
      description: 'Delete a blog post.',
      domain: 'blog',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { post_id: { type: 'string', description: 'Post id or slug.' } },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post_id: { type: 'string' }, deleted: { type: 'boolean' } },
        required: ['post_id', 'deleted'],
      },
    }),
]
