import type { McpToolDefinition } from './shared'
import { bookingPolicyObject, bookingPolicyWriteSchema, renderedBookingPolicySummaryObject, siteTool } from './shared'

const TENANT_PAGE_METADATA_SCHEMA = {
  path: { type: 'string' },
  title: { type: 'string' },
  summary: { type: ['string', 'null'] },
  seoTitle: { type: ['string', 'null'] },
  seoDescription: { type: ['string', 'null'] },
  canonicalUrl: { type: ['string', 'null'] },
  robots: { type: ['string', 'null'] },
  pageType: { type: 'string', enum: ['custom', 'recipe', 'legal', 'system'] },
  recipe: { type: ['string', 'null'] },
  sortOrder: { type: ['number', 'null'] },
}

const TENANT_PAGE_BLOCKS_SCHEMA = {
  type: 'array',
  items: { type: 'object' },
  description: 'Complete canonical block array. Each existing block must retain its id unless its removal is explicitly confirmed. Image blocks store asset_id only; never write a delivery URL. Use set_media for media placement.',
}

const TENANT_PAGE_LIFECYCLE_OUTPUT = {
  type: 'object',
  properties: { page: { type: 'object' }, replacement_confirmation: { type: 'object' }, revision_id: { type: ['string', 'null'] }, deleted: { type: 'boolean' }, id: { type: 'string' } },
}

export const CONTENT_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'get_page_fields',
      description: 'Get the current tenant page metadata and typed blocks. Call this before update_page_content to inspect the canonical page shape.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { page: { type: 'string' }, location_id: { type: 'string' } },
      required: ['page'],
      outputSchema: {
        type: 'object',
        properties: {
          page: { type: 'string' },
          siteId: { type: 'string' },
          locationId: { type: ['string', 'null'] },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
          fields: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                field: { type: 'string' },
                value: { type: ['string', 'null'] },
                render_status: { type: 'string', enum: ['rendered', 'orphan'] },
                editable_keys: { type: 'array', items: { type: 'string' } },
              },
            },
          },
          schema: {
            type: 'object',
            properties: {
              page: { type: 'string' },
              fields: { type: 'array', items: { type: 'string' } },
              structured: { type: 'array', items: { type: 'string' } },
            },
          },
          page_data: { type: 'object' },
          blocks: { type: 'array', items: { type: 'object' } },
        },
        required: ['page', 'siteId'],
      },
    }),
  siteTool({
      name: 'update_page_content',
      description: 'Replace a tenant page draft through the canonical editor. changes must include the complete typed blocks array plus any changed page metadata. Omitting existing block ids is destructive: include expected_document_updated_at, the exact removed_block_ids, and the confirmation_token returned by the canonical page read. Structured business data is edited through its own domain tool.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { page: { type: 'string' }, changes: { type: 'object' }, location_id: { type: 'string' } },
      required: ['page', 'changes'],
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          location_id: { type: ['string', 'null'] },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
  siteTool({
      name: 'list_tenant_pages',
      description: 'List canonical tenant-page variants for one manually managed locale. Automated translation is not used; create or update each locale explicitly.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { locale: { type: ['string', 'null'] } },
      outputSchema: { type: 'object', properties: { pages: { type: 'array', items: { type: 'object' } } }, required: ['pages'] },
    }),
  siteTool({
      name: 'get_tenant_page',
      description: 'Get one canonical tenant-page variant, including its current draft revision timestamp and blocks.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { variant_id: { type: 'string' } },
      required: ['variant_id'],
      outputSchema: TENANT_PAGE_LIFECYCLE_OUTPUT,
    }),
  siteTool({
      name: 'create_tenant_page',
      description: 'Create a manually authored tenant-page variant. A non-source locale must provide page_id for an existing source page; no automated translation is performed.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: {
        page_id: { type: ['string', 'null'] },
        variant_id: { type: ['string', 'null'] },
        locale: { type: ['string', 'null'] },
        ...TENANT_PAGE_METADATA_SCHEMA,
        blocks: TENANT_PAGE_BLOCKS_SCHEMA,
        publish: { type: 'boolean' },
      },
      required: ['path', 'title', 'blocks'],
      outputSchema: TENANT_PAGE_LIFECYCLE_OUTPUT,
    }),
  siteTool({
      name: 'update_tenant_page_draft',
      description: 'Update a canonical tenant-page draft with optimistic concurrency. Provide the complete blocks array and expected_document_updated_at from the last read. If existing block ids are omitted, also provide the exact removed_block_ids and confirmation_token returned by the canonical page read.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: {
        variant_id: { type: 'string' },
        expected_document_updated_at: { type: 'string' },
        ...TENANT_PAGE_METADATA_SCHEMA,
        blocks: TENANT_PAGE_BLOCKS_SCHEMA,
        removed_block_ids: { type: 'array', items: { type: 'string' } },
        confirmation_token: { type: 'string' },
      },
      required: ['variant_id', 'expected_document_updated_at', 'blocks'],
      outputSchema: TENANT_PAGE_LIFECYCLE_OUTPUT,
    }),
  siteTool({
      name: 'publish_tenant_page',
      description: 'Publish the current canonical tenant-page draft after checking its revision timestamp.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { variant_id: { type: 'string' }, expected_document_updated_at: { type: 'string' } },
      required: ['variant_id', 'expected_document_updated_at'],
      outputSchema: TENANT_PAGE_LIFECYCLE_OUTPUT,
    }),
  siteTool({
      name: 'unpublish_tenant_page',
      description: 'Remove the current published revision and leave the canonical tenant page as a draft.',
      domain: 'content',
      minimumRole: 'admin',
      confirmRequired: true,
      inputSchema: { variant_id: { type: 'string' }, expected_document_updated_at: { type: 'string' } },
      required: ['variant_id', 'expected_document_updated_at'],
      outputSchema: TENANT_PAGE_LIFECYCLE_OUTPUT,
    }),
  siteTool({
      name: 'change_tenant_page_path',
      description: 'Change a canonical tenant-page draft path. Publish the draft to activate the locale-scoped redirect; safe tenant-page redirect chains are flattened during publication.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { variant_id: { type: 'string' }, new_path: { type: 'string' }, expected_document_updated_at: { type: 'string' } },
      required: ['variant_id', 'new_path', 'expected_document_updated_at'],
      outputSchema: TENANT_PAGE_LIFECYCLE_OUTPUT,
    }),
  siteTool({
      name: 'archive_tenant_page',
      description: 'Archive a canonical tenant page. Supply a published replacement_path in the same locale or set gone=true for an explicit 410.',
      domain: 'content',
      minimumRole: 'admin',
      confirmRequired: true,
      inputSchema: { variant_id: { type: 'string' }, expected_document_updated_at: { type: 'string' }, replacement_path: { type: ['string', 'null'] }, gone: { type: 'boolean' } },
      required: ['variant_id', 'expected_document_updated_at'],
      outputSchema: TENANT_PAGE_LIFECYCLE_OUTPUT,
    }),
  siteTool({
      name: 'restore_tenant_page',
      description: 'Restore an archived canonical tenant-page variant to draft status.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { variant_id: { type: 'string' }, expected_document_updated_at: { type: 'string' } },
      required: ['variant_id', 'expected_document_updated_at'],
      outputSchema: TENANT_PAGE_LIFECYCLE_OUTPUT,
    }),
  siteTool({
      name: 'delete_tenant_page',
      description: 'Permanently delete a never-published canonical tenant-page variant after checking its revision timestamp and references.',
      domain: 'content',
      minimumRole: 'admin',
      confirmRequired: true,
      inputSchema: { variant_id: { type: 'string' }, expected_document_updated_at: { type: 'string' } },
      required: ['variant_id', 'expected_document_updated_at'],
      outputSchema: TENANT_PAGE_LIFECYCLE_OUTPUT,
    }),
  siteTool({
      name: 'get_professional_service_content',
      description: 'Get structured Blawby/professional-service data for a site: offerings, compliance text, consultation settings, navigation, and theme tokens. Page composition is managed through the canonical Pages tools.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {},
      outputSchema: {
        type: 'object',
        properties: {
          offerings: { type: 'array', items: { type: 'object' } },
          compliance: { type: ['object', 'null'] },
          consultation: { type: 'object' },
          navigation: { type: 'array', items: { type: 'object' } },
          themeTokens: { type: 'object' },
        },
        required: ['offerings', 'consultation', 'navigation', 'themeTokens'],
      },
    }),
  siteTool({
      name: 'update_professional_service_content',
      description: 'Create or update structured Blawby/professional-service data. Page composition is managed through the canonical Pages tools.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        offerings: { type: 'array', items: { type: 'object' } },
        compliance: {
          type: 'object',
          description: 'Canonical organization/compliance data used by every professional-service surface and its schema.org graph.',
          properties: {
            entity_name: { type: ['string', 'null'] },
            dba_name: { type: ['string', 'null'] },
            entity_type: { type: ['string', 'null'], description: 'Schema.org type name such as LegalService or AccountingService.' },
            nonprofit_status: { type: ['string', 'null'], description: 'Recognized schema.org nonprofit enumeration URL or a normalizable form such as 501(c)(3).' },
            registration_number: { type: ['string', 'null'] },
            service_area: { type: ['string', 'null'] },
            service_area_type: { type: ['string', 'null'], enum: ['AdministrativeArea', 'City', 'Country', 'Place', 'State', null] },
            founder_name: { type: ['string', 'null'] },
            founding_date: { type: ['string', 'null'], description: 'ISO calendar date in YYYY-MM-DD format.' },
            same_as: { type: 'array', items: { type: 'string' }, description: 'Absolute HTTP(S) social or identity profile URLs.' },
            contact_points: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  contact_type: { type: ['string', 'null'] },
                  telephone: { type: ['string', 'null'] },
                  email: { type: ['string', 'null'] },
                  area_served: { type: ['string', 'null'] },
                  available_language: { type: ['array', 'string', 'null'], items: { type: 'string' } },
                  url: { type: ['string', 'null'] },
                },
              },
            },
            address_visibility: { type: 'string', enum: ['visible', 'hidden'] },
            disclaimer: { type: ['string', 'null'] },
            footer_disclaimer: { type: ['string', 'null'] },
            document_asset_ids: { type: 'array', items: { type: 'string' } },
            metadata: { type: 'object' },
          },
        },
        consultation: { type: 'object' },
        navigation: { type: 'array', items: { type: 'object' } },
        themeTokens: { type: 'object' },
      },
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          written: { type: 'object' },
        },
        required: ['success', 'written'],
      },
    }),
  siteTool({
      name: 'get_booking_policy',
      description: 'Get the canonical structured booking policy for reservations or experiences. Use scope_type=site for the site default, scope_type=location for a location override, or scope_type=experience for an experience-specific override.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        policy_type: bookingPolicyWriteSchema.policy_type,
        scope_type: bookingPolicyWriteSchema.scope_type,
        location_id: bookingPolicyWriteSchema.location_id,
        experience_id: bookingPolicyWriteSchema.experience_id,
        locale: bookingPolicyWriteSchema.locale,
      },
      required: ['policy_type'],
      outputSchema: {
        type: 'object',
        properties: {
          policy: bookingPolicyObject,
          resolved_policy: bookingPolicyObject,
          summary: renderedBookingPolicySummaryObject,
        },
        required: ['resolved_policy', 'summary'],
      },
    }),
  siteTool({
      name: 'preview_booking_policy',
      description: 'Preview how structured booking policy changes will render without saving them.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: bookingPolicyWriteSchema,
      required: ['policy_type'],
      outputSchema: {
        type: 'object',
        properties: {
          resolved_policy: bookingPolicyObject,
          summary: renderedBookingPolicySummaryObject,
        },
        required: ['resolved_policy', 'summary'],
      },
    }),
  siteTool({
      name: 'update_booking_policy',
      description: 'Create or update the canonical structured booking policy for reservations or experiences. Use this instead of editing reservation policy prose or experience cancellation text directly.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: bookingPolicyWriteSchema,
      required: ['policy_type'],
      outputSchema: {
        type: 'object',
        properties: {
          ok: { type: 'boolean' },
          entity: { type: 'string', enum: ['booking_policy'] },
          id: { type: 'string' },
          policy_type: { type: 'string' },
          scope_type: { type: 'string' },
          changed_fields: { type: 'array', items: { type: 'string' } },
          updated_at: { type: 'string' },
          context: { type: 'object' },
          summary: renderedBookingPolicySummaryObject,
        },
        required: ['ok', 'entity', 'id'],
      },
    }),
  siteTool({
      name: 'update_home_hero',
      description: 'Update the homepage hero text — this affects the homepage, never a location\'s own separate page. If the user is talking about one particular location\'s own page (e.g. a closure or an announcement image for one location), use update_location instead. To place media, call set_media with target home_hero. Only provided fields are changed.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        title: { type: 'string' },
        subtitle: { type: 'string' },
        location_id: { type: 'string', description: 'Not supported for the site-scoped homepage.' },
      },
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
]
