import type { McpToolDefinition } from './shared'
import { bookingPolicyObject, bookingPolicyWriteSchema, renderedBookingPolicySummaryObject, siteTool } from './shared'

export const CONTENT_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'get_page_fields',
      description: 'Get editable field definitions and current values for a page. Call this before update_page_content to see which fields exist and what they are set to.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { page: { type: 'string' }, location_id: { type: 'string' } },
      required: ['page'],
      outputSchema: {
        type: 'object',
        properties: {
          page: { type: 'string' },
          siteId: { type: 'string' },
          locationId: { type: ['string', 'null'] },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
          fields: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                field: { type: 'string' },
                value: { type: ['string', 'null'] },
                render_status: { type: 'string', enum: ['rendered', 'orphan'] },
                editable_keys: { type: 'array', items: { type: 'string' } },
              },
            },
          },
          schema: {
            type: 'object',
            properties: {
              page: { type: 'string' },
              fields: { type: 'array', items: { type: 'string' } },
              structured: { type: 'array', items: { type: 'string' } },
            },
          },
        },
        required: ['page', 'siteId', 'fields'],
      },
    }),
  siteTool({
      name: 'update_page_content',
      description: 'Update canonical page content directly. Validates field names against the page schema and writes live renderer-bound content immediately.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { page: { type: 'string' }, changes: { type: 'object' }, location_id: { type: 'string' } },
      required: ['page', 'changes'],
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          location_id: { type: ['string', 'null'] },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
  siteTool({
      name: 'get_professional_service_content',
      description: 'Get Blawby/professional-service content for a site: offerings, tenant pages, compliance text, consultation settings, navigation, and theme tokens.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {},
      outputSchema: {
        type: 'object',
        properties: {
          offerings: { type: 'array', items: { type: 'object' } },
          tenantPages: { type: 'array', items: { type: 'object' } },
          compliance: { type: ['object', 'null'] },
          consultation: { type: 'object' },
          navigation: { type: 'array', items: { type: 'object' } },
          themeTokens: { type: 'object' },
        },
        required: ['offerings', 'tenantPages', 'consultation', 'navigation', 'themeTokens'],
      },
    }),
  siteTool({
      name: 'update_professional_service_content',
      description: 'Create or update Blawby/professional-service content. Use structured calculator components only; arbitrary formulas, scripts, or expressions are rejected.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        offerings: { type: 'array', items: { type: 'object' } },
        tenantPages: { type: 'array', items: { type: 'object' } },
        compliance: {
          type: 'object',
          description: 'Canonical organization/compliance data used by every professional-service surface and its schema.org graph.',
          properties: {
            entity_name: { type: ['string', 'null'] },
            dba_name: { type: ['string', 'null'] },
            entity_type: { type: ['string', 'null'], description: 'Schema.org type name such as LegalService or AccountingService.' },
            nonprofit_status: { type: ['string', 'null'], description: 'Recognized schema.org nonprofit enumeration URL or a normalizable form such as 501(c)(3).' },
            registration_number: { type: ['string', 'null'] },
            service_area: { type: ['string', 'null'] },
            service_area_type: { type: ['string', 'null'], enum: ['AdministrativeArea', 'City', 'Country', 'Place', 'State', null] },
            founder_name: { type: ['string', 'null'] },
            founding_date: { type: ['string', 'null'], description: 'ISO calendar date in YYYY-MM-DD format.' },
            same_as: { type: 'array', items: { type: 'string' }, description: 'Absolute HTTP(S) social or identity profile URLs.' },
            contact_points: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  contact_type: { type: ['string', 'null'] },
                  telephone: { type: ['string', 'null'] },
                  email: { type: ['string', 'null'] },
                  area_served: { type: ['string', 'null'] },
                  available_language: { type: ['array', 'string', 'null'], items: { type: 'string' } },
                  url: { type: ['string', 'null'] },
                },
              },
            },
            address_visibility: { type: 'string', enum: ['visible', 'hidden'] },
            disclaimer: { type: ['string', 'null'] },
            footer_disclaimer: { type: ['string', 'null'] },
            document_asset_ids: { type: 'array', items: { type: 'string' } },
            metadata: { type: 'object' },
          },
        },
        consultation: { type: 'object' },
        navigation: { type: 'array', items: { type: 'object' } },
        themeTokens: { type: 'object' },
      },
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          written: { type: 'object' },
        },
        required: ['success', 'written'],
      },
    }),
  siteTool({
      name: 'get_booking_policy',
      description: 'Get the canonical structured booking policy for reservations or experiences. Use scope_type=site for the site default, scope_type=location for a location override, or scope_type=experience for an experience-specific override.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        policy_type: bookingPolicyWriteSchema.policy_type,
        scope_type: bookingPolicyWriteSchema.scope_type,
        location_id: bookingPolicyWriteSchema.location_id,
        experience_id: bookingPolicyWriteSchema.experience_id,
        locale: bookingPolicyWriteSchema.locale,
      },
      required: ['policy_type'],
      outputSchema: {
        type: 'object',
        properties: {
          policy: bookingPolicyObject,
          resolved_policy: bookingPolicyObject,
          summary: renderedBookingPolicySummaryObject,
        },
        required: ['resolved_policy', 'summary'],
      },
    }),
  siteTool({
      name: 'preview_booking_policy',
      description: 'Preview how structured booking policy changes will render without saving them.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: bookingPolicyWriteSchema,
      required: ['policy_type'],
      outputSchema: {
        type: 'object',
        properties: {
          resolved_policy: bookingPolicyObject,
          summary: renderedBookingPolicySummaryObject,
        },
        required: ['resolved_policy', 'summary'],
      },
    }),
  siteTool({
      name: 'update_booking_policy',
      description: 'Create or update the canonical structured booking policy for reservations or experiences. Use this instead of editing reservation policy prose or experience cancellation text directly.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: bookingPolicyWriteSchema,
      required: ['policy_type'],
      outputSchema: {
        type: 'object',
        properties: {
          ok: { type: 'boolean' },
          entity: { type: 'string', enum: ['booking_policy'] },
          id: { type: 'string' },
          policy_type: { type: 'string' },
          scope_type: { type: 'string' },
          changed_fields: { type: 'array', items: { type: 'string' } },
          updated_at: { type: 'string' },
          context: { type: 'object' },
          summary: renderedBookingPolicySummaryObject,
        },
        required: ['ok', 'entity', 'id'],
      },
    }),
  siteTool({
      name: 'update_home_hero',
      description: 'Update the homepage hero text — this affects the homepage, never a location\'s own separate page. If the user is talking about one particular location\'s own page (e.g. a closure or an announcement image for one location), use update_location instead. To place media, call set_media with target home_hero. Only provided fields are changed.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        title: { type: 'string' },
        subtitle: { type: 'string' },
        location_id: { type: 'string', description: 'Optional location scope when the homepage content is location-specific.' },
      },
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
  siteTool({
      name: 'delete_content_field',
      description: 'Delete a canonical content field from live page content.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { page: { type: 'string' }, field: { type: 'string' }, location_id: { type: 'string' } },
      required: ['page', 'field'],
      outputSchema: {
        type: 'object',
        properties: {
          deleted: { type: 'boolean' },
          field: { type: 'string' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['deleted'],
      },
    }),
]
