import type { McpToolDefinition } from './shared'
import { bookingPolicyObject, bookingPolicyWriteSchema, renderedBookingPolicySummaryObject, siteTool } from './shared'
import { MEDIA_UPLOAD_WIDGET_RESOURCE_URI } from '~/server/utils/mcp-widgets'

export const CONTENT_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'get_page_fields',
      description: 'Get editable field definitions and current values for a page. Call this before update_page_content to see which fields exist and what they are set to.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { page: { type: 'string' }, location_id: { type: 'string' } },
      required: ['page'],
      outputSchema: {
        type: 'object',
        properties: {
          page: { type: 'string' },
          siteId: { type: 'string' },
          locationId: { type: ['string', 'null'] },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
          fields: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                field: { type: 'string' },
                value: { type: ['string', 'null'] },
                render_status: { type: 'string', enum: ['rendered', 'orphan'] },
                editable_keys: { type: 'array', items: { type: 'string' } },
              },
            },
          },
          schema: {
            type: 'object',
            properties: {
              page: { type: 'string' },
              fields: { type: 'array', items: { type: 'string' } },
              structured: { type: 'array', items: { type: 'string' } },
            },
          },
        },
        required: ['page', 'siteId', 'fields'],
      },
    }),
  siteTool({
      name: 'update_page_content',
      description: 'Update canonical page content directly. Validates field names against the page schema and writes live renderer-bound content immediately.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { page: { type: 'string' }, changes: { type: 'object' }, location_id: { type: 'string' } },
      required: ['page', 'changes'],
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          location_id: { type: ['string', 'null'] },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
  siteTool({
      name: 'get_booking_policy',
      description: 'Get the canonical structured booking policy for reservations or experiences. Use scope_type=site for the site default, scope_type=location for a location override, or scope_type=experience for an experience-specific override.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        policy_type: bookingPolicyWriteSchema.policy_type,
        scope_type: bookingPolicyWriteSchema.scope_type,
        location_id: bookingPolicyWriteSchema.location_id,
        experience_id: bookingPolicyWriteSchema.experience_id,
        locale: bookingPolicyWriteSchema.locale,
      },
      required: ['policy_type'],
      outputSchema: {
        type: 'object',
        properties: {
          policy: bookingPolicyObject,
          resolved_policy: bookingPolicyObject,
          summary: renderedBookingPolicySummaryObject,
        },
        required: ['resolved_policy', 'summary'],
      },
    }),
  siteTool({
      name: 'preview_booking_policy',
      description: 'Preview how structured booking policy changes will render without saving them.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: bookingPolicyWriteSchema,
      required: ['policy_type'],
      outputSchema: {
        type: 'object',
        properties: {
          resolved_policy: bookingPolicyObject,
          summary: renderedBookingPolicySummaryObject,
        },
        required: ['resolved_policy', 'summary'],
      },
    }),
  siteTool({
      name: 'update_booking_policy',
      description: 'Create or update the canonical structured booking policy for reservations or experiences. Use this instead of editing reservation policy prose or experience cancellation text directly.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: bookingPolicyWriteSchema,
      required: ['policy_type'],
      outputSchema: {
        type: 'object',
        properties: {
          ok: { type: 'boolean' },
          entity: { type: 'string', enum: ['booking_policy'] },
          id: { type: 'string' },
          policy_type: { type: 'string' },
          scope_type: { type: 'string' },
          changed_fields: { type: 'array', items: { type: 'string' } },
          updated_at: { type: 'string' },
          context: { type: 'object' },
          summary: renderedBookingPolicySummaryObject,
        },
        required: ['ok', 'entity', 'id'],
      },
    }),
  siteTool({
      name: 'update_home_hero',
      description: 'Update the homepage hero (title, subtitle, hero image, or hero video) — this affects the homepage, never a location\'s own separate page. If the user is talking about one particular location\'s own page (e.g. a closure, an announcement image for one location), use update_location instead. To assign an existing media asset as the hero image: call get_site_media_assets first to get its id, then pass it as image_asset_id here. Only provided fields are changed — omitting image_asset_id leaves the existing hero image intact.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        title: { type: 'string' },
        subtitle: { type: 'string' },
        image_asset_id: { type: 'string' },
        video_asset_id: { type: 'string' },
        location_id: { type: 'string', description: 'Optional location scope when the homepage content is location-specific.' },
      },
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
  siteTool({
      name: 'set_home_hero_image',
      description: 'Use this when the user wants to change the main photo at the top of the homepage — also called the cover photo, banner, big photo, first image people see, or hero image. Call get_site_media_assets first to find an active image asset id, then pass it here as asset_id. Use this immediately after upload_user_photo when the user wants their uploaded image on the homepage. If this page already has a hero video, that video keeps display priority until you call clear_home_hero_video.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        asset_id: { type: 'string', description: 'Active image asset id from get_site_media_assets.' },
        location_id: { type: 'string', description: 'Optional location scope when the homepage content is location-specific.' },
      },
      required: ['asset_id'],
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          asset_id: { type: 'string' },
          public_url: { type: ['string', 'null'] },
          view_url: { type: ['string', 'null'] },
          asset_public_url: { type: ['string', 'null'] },
          warning: { type: 'string' },
        },
        required: ['success', 'page', 'changes_count', 'asset_id'],
      },
    }),
  siteTool({
      name: 'set_home_hero_video',
      description: 'Assign a saved video asset as the homepage hero video. Upload the video first via open_home_hero_media_upload (or upload_user_media if you already have a resolved file reference), then call get_site_media_assets to find its asset id. Hero videos take display priority over any existing hero image for the same page.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        asset_id: { type: 'string', description: 'Active video asset id from get_site_media_assets.' },
        location_id: { type: 'string', description: 'Optional location scope when the homepage content is location-specific.' },
      },
      required: ['asset_id'],
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
          warning: { type: 'string' },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
  siteTool({
      name: 'clear_home_hero_image',
      description: 'Clear the current homepage hero image without affecting the hero video.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        location_id: { type: 'string', description: 'Optional location scope when the homepage content is location-specific.' },
      },
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
  siteTool({
      name: 'clear_home_hero_video',
      description: 'Clear the current homepage hero video without affecting the hero image.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        location_id: { type: 'string', description: 'Optional location scope when the homepage content is location-specific.' },
      },
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
  siteTool({
      name: 'open_home_hero_media_upload',
      description: 'Launches the inline media upload widget scoped to the homepage hero — image or video. After the widget reports a completed upload, call set_home_hero_image or set_home_hero_video with the returned assetId.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      uiResourceUri: MEDIA_UPLOAD_WIDGET_RESOURCE_URI,
      inputSchema: {
        location_id: { type: 'string', description: 'Optional location scope when the homepage content is location-specific.' },
        accept: { type: 'string', enum: ['image', 'video', 'both'], description: 'Restrict the widget file picker. Defaults to both.' },
      },
      outputSchema: {
        type: 'object',
        properties: {
          launched: { type: 'boolean' },
          resourceUri: { type: 'string' },
        },
        required: ['launched', 'resourceUri'],
      },
    }),
  siteTool({
      name: 'set_about_story_image',
      description: 'Use this when the user wants to change the photo beside the story or about-us text on the About page (/about). Call get_site_media_assets first to find an active image asset id, then pass it here as asset_id. Use set_home_story_image instead if the user means the story section on the homepage — the two pages have separate story.image fields and this tool only ever writes to /about. It is common to reuse the same asset_id for both.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        asset_id: { type: 'string', description: 'Active image asset id from get_site_media_assets.' },
      },
      required: ['asset_id'],
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
  siteTool({
      name: 'set_home_story_image',
      description: 'Use this when the user wants to change the photo beside the story or about-us text on the homepage (/). Call get_site_media_assets first to find an active image asset id, then pass it here as asset_id. Use set_about_story_image instead if the user means the story section on the About page — the two pages have separate story.image fields and this tool only ever writes to home. It is common to reuse the same asset_id for both.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        asset_id: { type: 'string', description: 'Active image asset id from get_site_media_assets.' },
      },
      required: ['asset_id'],
      outputSchema: {
        type: 'object',
        properties: {
          success: { type: 'boolean' },
          page: { type: 'string' },
          changes_count: { type: 'number' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['success', 'page', 'changes_count'],
      },
    }),
  siteTool({
      name: 'delete_content_field',
      description: 'Delete a canonical content field from live page content.',
      domain: 'content',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { page: { type: 'string' }, field: { type: 'string' }, location_id: { type: 'string' } },
      required: ['page', 'field'],
      outputSchema: {
        type: 'object',
        properties: {
          deleted: { type: 'boolean' },
          field: { type: 'string' },
          public_path: { type: 'string' },
          view_url: { type: ['string', 'null'] },
        },
        required: ['deleted'],
      },
    }),
]
