import type { McpToolDefinition } from './shared'
import { chatgptFileInput, mediaAssetObject, resolvedMediaAssetObject, siteTool } from './shared'

export const MEDIA_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'set_media',
      description: 'Assign existing media assets to a CMS placement. Uploading and placement are separate: call upload_user_media to create reusable media_assets, get_site_media_assets to choose asset ids, then set_media to replace the complete desired media state for the target. asset_ids order is authoritative; empty asset_ids clears the target. Position 0 is the cover for ordered mixed-media targets. Video cover/hero assets must already have thumbnail_url/poster metadata.',
      domain: 'media',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        target: {
          type: 'object',
          description: 'Discriminated media placement target. Supported types: site_logo, home_hero, home_story_image, about_story_image, location_hero, menu_item_image, post_image, blog_post_image, experience_media.',
          oneOf: [
            { properties: { type: { const: 'site_logo' } }, required: ['type'] },
            { properties: { type: { const: 'home_hero' }, location_id: { type: ['string', 'null'] } }, required: ['type'] },
            { properties: { type: { const: 'home_story_image' } }, required: ['type'] },
            { properties: { type: { const: 'about_story_image' } }, required: ['type'] },
            { properties: { type: { const: 'location_hero' }, location_id: { type: 'string' } }, required: ['type', 'location_id'] },
            { properties: { type: { const: 'menu_item_image' }, menu_item_id: { type: 'string' } }, required: ['type', 'menu_item_id'] },
            { properties: { type: { const: 'post_image' }, post_id: { type: 'string' } }, required: ['type', 'post_id'] },
            { properties: { type: { const: 'blog_post_image' }, post_id: { type: 'string' } }, required: ['type', 'post_id'] },
            { properties: { type: { const: 'experience_media' }, experience_id: { type: 'string' } }, required: ['type', 'experience_id'] },
          ],
        },
        asset_ids: {
          type: 'array',
          items: { type: 'string' },
          uniqueItems: true,
          description: 'Complete desired asset-id state for the target. Empty clears. Duplicates are rejected.',
        },
        allOf: [
          {
            if: { properties: { target: { properties: { type: { const: 'experience_media' } } } } },
            then: {},
            else: { properties: { asset_ids: { maxItems: 1 } } },
          },
        ],
      },
      required: ['target', 'asset_ids'],
      outputSchema: {
        type: 'object',
        properties: {
          ok: { type: 'boolean' },
          entity: { type: 'string' },
          id: { type: 'string' },
          target: { type: 'object' },
          asset_ids: { type: 'array', items: { type: 'string' } },
          media: { type: 'array', items: resolvedMediaAssetObject },
          cleared: { type: 'boolean' },
          updated_at: { type: ['string', 'null'] },
          location_id: { type: ['string', 'null'] },
          context: { type: 'object' },
        },
        required: ['ok', 'entity', 'id', 'target', 'asset_ids', 'media', 'cleared'],
      },
    }),
  siteTool({
      name: 'get_site_media_assets',
      description: 'Use this to see the photos and videos already uploaded for a site — "what pictures do I have", "show me my photos". Use it first to find asset IDs before assigning media with set_media. Filter by kind="image" or kind="video" to narrow results. New user-provided media uses upload_user_media with a native ChatGPT attachment. There are no upload widget tools in this connector.',
      domain: 'media',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { kind: { type: 'string', description: 'Filter by asset type: "image" or "video".' }, location_id: { type: 'string' } },
      outputSchema: {
        type: 'object',
        properties: { assets: { type: 'array', items: mediaAssetObject } },
        required: ['assets'],
      },
    }),
  siteTool({
      name: 'upload_user_media',
      description: 'The only upload path for user-provided images, videos, and Markdown documents (.md/.markdown). Accepts a resolved native ChatGPT file reference and validates the actual bytes. The returned asset_id is active and immediately assignable. For a video, poster_file may provide a thumbnail. Only call this tool when the host supplied a real file/file_id reference; never invent one. Do not call upload widget tools; no tool whose name starts with "open_" and contains "upload" exists.',
      domain: 'media',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        file: chatgptFileInput,
        file_id: { type: 'string', description: 'Resolved file identifier for a user-uploaded image, video, or Markdown document (e.g. file_abc123). Prefer file when the host can supply the filename directly.' },
        poster_file: { ...chatgptFileInput, description: 'Optional poster/thumbnail image for a video upload. Ignored for image uploads.' },
        category: { type: 'string', enum: ['exterior', 'interior', 'food', 'menu', 'team', 'logo', 'blog', 'other'], description: 'What this media will be used for.' },
        description: { type: 'string', description: 'Description of the media (stored as alt text).' },
        oneOf: [
          { required: ['file'] },
          { required: ['file_id'] },
        ],
      },
      required: [],
      fileParams: ['file', 'poster_file'],
      outputSchema: {
        type: 'object',
        properties: {
          asset_id: { type: 'string' },
          public_url: { type: 'string' },
          status: { type: 'string', enum: ['active'] },
          thumbnail_url: { type: ['string', 'null'] },
          kind: { type: 'string', enum: ['image', 'video', 'file'] },
          poster_warning: { type: ['string', 'null'] },
          next_step: { type: 'string' },
        },
        required: ['asset_id', 'status', 'public_url', 'kind'],
      },
    }),
  siteTool({
      name: 'update_media_asset',
      description: 'Update media metadata.',
      domain: 'media',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { asset_id: { type: 'string' }, alt_text: { type: 'string' }, location_id: { type: 'string' }, category: { type: 'string' } },
      required: ['asset_id'],
      outputSchema: {
        type: 'object',
        properties: { updated: mediaAssetObject },
        required: ['updated'],
      },
    }),
  siteTool({
      name: 'delete_media_asset',
      description: 'Delete a media asset.',
      domain: 'media',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { asset_id: { type: 'string' } },
      required: ['asset_id'],
      outputSchema: {
        type: 'object',
        properties: { deleted: { type: 'boolean' } },
        required: ['deleted'],
      },
    }),
  siteTool({
      name: 'import_menu_from_media',
      description: 'Extract and add menu items from a menu photo or PDF.',
      domain: 'media',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { asset_id: { type: 'string' }, menu_name: { type: 'string' } },
      required: ['asset_id'],
      outputSchema: {
        type: 'object',
        properties: {
          menu: {
            type: 'object',
            description: 'Created menu.',
            properties: {
              id: { type: 'string' },
              name: { type: 'string' },
            },
            required: ['id', 'name'],
          },
          items_created: { type: 'number', description: 'Number of menu items extracted and created.' },
        },
        required: ['menu'],
      },
    }),
  siteTool({
      name: 'analyze_document',
      description: 'Summarize, answer questions about, or extract information from an uploaded Markdown document (.md/.markdown), grounded strictly in that file. Use upload_user_media with the attached Markdown file or get_site_media_assets to obtain its asset_id. Pass a question for grounded Q&A; omit it for a summary.',
      domain: 'media',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        asset_id: { type: 'string', description: 'Media asset ID of the uploaded Markdown document.' },
        question: { type: 'string', description: 'Optional question to answer using only the document content. Omit for a summary.' },
      },
      required: ['asset_id'],
      outputSchema: {
        type: 'object',
        properties: {
          answer: { type: 'string', description: 'Grounded answer or summary.' },
          creditsRemaining: { type: 'number', description: 'AI credits remaining after document analysis.' },
          stats: {
            type: 'object',
            description: 'Structural stats detected in the document.',
            properties: {
              headings: { type: 'number' },
              listItems: { type: 'number' },
              tableRows: { type: 'number' },
              codeBlocks: { type: 'number' },
              blockquotes: { type: 'number' },
              links: { type: 'number' },
            },
          },
        },
        required: ['answer', 'creditsRemaining', 'stats'],
      },
    }),
]
