import type { McpToolDefinition } from './shared'
import { menuItemObject, menuObject, siteTool } from './shared'
import { MEDIA_UPLOAD_WIDGET_RESOURCE_URI } from '~/server/utils/mcp-widgets'

export const MENUS_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'list_menus',
      description: 'List menus.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      outputSchema: {
        type: 'object',
        properties: {
          menus: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                description: { type: ['string', 'null'] },
                location_id: { type: ['string', 'null'] },
                sort_order: { type: 'number' },
              },
              required: ['id', 'name'],
            },
          },
        },
        required: ['menus'],
      },
    }),
  siteTool({
      name: 'get_menu',
      description: 'Get a menu with items.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { menu_id: { type: 'string' } },
      required: ['menu_id'],
      outputSchema: {
        type: 'object',
        properties: { menu: menuObject },
        required: ['menu'],
      },
    }),
  siteTool({
      name: 'create_menu',
      description: 'Create a menu.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { name: { type: 'string' }, location_id: { type: 'string' }, description: { type: 'string' } },
      required: ['name'],
      outputSchema: {
        type: 'object',
        properties: {
          menu: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              name: { type: 'string' },
              description: { type: ['string', 'null'] },
              location_id: { type: ['string', 'null'] },
            },
            required: ['id', 'name'],
          },
        },
        required: ['menu'],
      },
    }),
  siteTool({
      name: 'update_menu',
      description: 'Update a menu.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        menu_id: { type: 'string' },
        name: { type: 'string' },
        description: { type: 'string' },
        status: { type: 'string', enum: ['draft', 'published'] },
        section_order: { type: 'array', items: { type: 'string' }, description: 'Section names in display order.' },
      },
      required: ['menu_id'],
      outputSchema: {
        type: 'object',
        properties: {
          menu: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              name: { type: 'string' },
              description: { type: ['string', 'null'] },
              status: { type: 'string' },
            },
            required: ['id'],
          },
        },
        required: ['menu'],
      },
    }),
  siteTool({
      name: 'delete_menu',
      description: 'Delete a menu.',
      domain: 'menus',
      minimumRole: 'admin',
      confirmRequired: true,
      inputSchema: { menu_id: { type: 'string' } },
      required: ['menu_id'],
      outputSchema: {
        type: 'object',
        properties: { deleted: { type: 'boolean' } },
        required: ['deleted'],
      },
    }),
  siteTool({
      name: 'create_menu_item',
      description: 'Create a menu item.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        menu_id: { type: 'string' },
        section: { type: 'string', description: 'Required menu section name, for example Cocktails, Mains, or Desserts.' },
        name: { type: 'string' },
        description: { type: ['string', 'null'] },
        price_amount: { type: ['string', 'number', 'null'], description: 'Canonical price field for menu items.' },
        price: { type: ['string', 'number', 'null'], description: 'Legacy alias accepted for compatibility. Prefer price_amount.' },
        image_asset_id: { type: ['string', 'null'] },
        available: { type: 'boolean' },
        featured: { type: 'boolean' },
        featured_sort_order: { type: 'number' },
        sort_order: { type: 'number' },
        allergens: { type: 'array', items: { type: 'string' } },
        ingredients: { type: 'array', items: { type: 'string' } },
        dietary_notes: { type: 'array', items: { type: 'string' } },
        preparation: { type: ['string', 'null'] },
        serving_note: { type: ['string', 'null'] },
      },
      required: ['menu_id', 'section', 'name'],
      outputSchema: {
        type: 'object',
        properties: { item: menuItemObject },
        required: ['item'],
      },
    }),
  siteTool({
      name: 'add_menu_items_batch',
      description: 'Add multiple brand-new menu items in one call. Use this when the user is adding new items, not revising existing ones.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        menu_id: { type: 'string' },
        items: {
          type: 'array',
          description: 'Up to 100 new menu items to add.',
          items: {
            type: 'object',
            properties: {
              section: { type: 'string', description: 'Required menu section name, for example Cocktails, Mains, or Desserts.' },
              name: { type: 'string' },
              description: { type: ['string', 'null'] },
              price_amount: { type: ['string', 'number', 'null'], description: 'Canonical price field for menu items.' },
              price: { type: ['string', 'number', 'null'], description: 'Legacy alias accepted for compatibility. Prefer price_amount.' },
              image_asset_id: { type: ['string', 'null'] },
              available: { type: 'boolean' },
              featured: { type: 'boolean' },
              featured_sort_order: { type: 'number' },
              sort_order: { type: 'number' },
              allergens: { type: 'array', items: { type: 'string' } },
              ingredients: { type: 'array', items: { type: 'string' } },
              dietary_notes: { type: 'array', items: { type: 'string' } },
              preparation: { type: ['string', 'null'] },
              serving_note: { type: ['string', 'null'] },
            },
            required: ['section', 'name'],
            additionalProperties: true,
          },
        },
      },
      required: ['menu_id', 'items'],
      outputSchema: {
        type: 'object',
        properties: {
          added: { type: 'number' },
          created: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                section: { type: 'string' },
                price_amount: { type: ['string', 'number', 'null'] },
              },
              required: ['id', 'name', 'section'],
            },
          },
          skipped: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                name: { type: 'string' },
                reason: { type: 'string' },
                existing_item_id: { type: ['string', 'null'] },
              },
              required: ['name', 'reason'],
            },
          },
          menu_id: { type: 'string' },
        },
        required: ['added', 'created', 'skipped', 'menu_id'],
      },
    }),
  siteTool({
      name: 'update_menu_item',
      description: 'Update a menu item.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        menu_item_id: { type: 'string' },
        section: { type: 'string' },
        name: { type: 'string' },
        description: { type: ['string', 'null'] },
        price_amount: { type: ['string', 'number', 'null'], description: 'Canonical price field for menu items.' },
        price: { type: ['string', 'number', 'null'], description: 'Legacy alias accepted for compatibility. Prefer price_amount.' },
        image_asset_id: { type: ['string', 'null'] },
        available: { type: 'boolean' },
        featured: { type: 'boolean' },
        featured_sort_order: { type: 'number' },
        sort_order: { type: 'number' },
        allergens: { type: 'array', items: { type: 'string' } },
        ingredients: { type: 'array', items: { type: 'string' } },
        dietary_notes: { type: 'array', items: { type: 'string' } },
        preparation: { type: ['string', 'null'] },
        serving_note: { type: ['string', 'null'] },
      },
      required: ['menu_item_id'],
      outputSchema: {
        type: 'object',
        properties: { item: menuItemObject },
        required: ['item'],
      },
    }),
  siteTool({
      name: 'set_menu_item_image',
      description: 'Use this when the user wants to add or change the photo of a specific dish or menu item — "add a picture of this dish". Call get_site_media_assets first to find an active image asset id, then pass it here with the target menu_item_id.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        menu_item_id: { type: 'string' },
        asset_id: { type: 'string', description: 'Active image asset id from get_site_media_assets.' },
      },
      required: ['menu_item_id', 'asset_id'],
      outputSchema: {
        type: 'object',
        properties: { item: menuItemObject },
        required: ['item'],
      },
    }),
  siteTool({
      name: 'open_menu_item_media_upload',
      description: 'Launches the inline media upload widget scoped to a specific menu item — image only for menu items today. After the widget reports a completed upload, call set_menu_item_image with the returned assetId and this menu_item_id.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      uiResourceUri: MEDIA_UPLOAD_WIDGET_RESOURCE_URI,
      inputSchema: {
        menu_item_id: { type: 'string' },
      },
      required: ['menu_item_id'],
      outputSchema: {
        type: 'object',
        properties: {
          launched: { type: 'boolean' },
          resourceUri: { type: 'string' },
          menu_item_id: { type: 'string' },
        },
        required: ['launched', 'resourceUri', 'menu_item_id'],
      },
    }),
  siteTool({
      name: 'delete_menu_item',
      description: 'Delete a menu item.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { menu_item_id: { type: 'string' } },
      required: ['menu_item_id'],
      outputSchema: {
        type: 'object',
        properties: { deleted: { type: 'boolean' } },
        required: ['deleted'],
      },
    }),
  siteTool({
      name: 'rename_menu_section',
      description: 'Rename a menu section.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { menu_id: { type: 'string' }, old_name: { type: 'string' }, new_name: { type: 'string' } },
      required: ['menu_id', 'old_name', 'new_name'],
      outputSchema: {
        type: 'object',
        properties: {
          updated: { type: 'number', description: 'Number of items renamed.' },
        },
        required: ['updated'],
      },
    }),
  siteTool({
      name: 'delete_menu_section',
      description: 'Delete a menu section.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { menu_id: { type: 'string' }, section_name: { type: 'string' } },
      required: ['menu_id', 'section_name'],
      outputSchema: {
        type: 'object',
        properties: {
          deleted: { type: 'number', description: 'Number of items deleted.' },
        },
        required: ['deleted'],
      },
    }),
  siteTool({
      name: 'reorder_menu_items',
      description: 'Reorder menu items.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { menu_id: { type: 'string' }, updates: { type: 'array' } },
      required: ['menu_id', 'updates'],
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean' } },
        required: ['updated'],
      },
    }),
]
