import type { McpToolDefinition } from './shared'
import { menuItemMutationResultObject, menuMutationResultObject, menuObject, pageInfoObject, paginationInputSchema, seoOverrideFieldsSchema, siteTool } from './shared'
import { MAX_MENU_BATCH_ITEMS, MAX_MENU_ITEM_MEDIA } from '~/server/utils/menu-batch-limits'

export const MENUS_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'list_menus',
      description: 'List menus.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { ...paginationInputSchema },
      outputSchema: {
        type: 'object',
        properties: {
          menus: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                description: { type: ['string', 'null'] },
                location_id: { type: ['string', 'null'] },
                is_visible: { type: 'boolean' },
                section_order: { type: ['array', 'null'], items: { type: 'string' } },
                updated_at: { type: 'string' },
              },
              required: ['id', 'name', 'is_visible', 'updated_at'],
            },
          },
          page_info: pageInfoObject,
        },
        required: ['menus', 'page_info'],
      },
    }),
  siteTool({
      name: 'get_menu',
      description: 'Get one page of a menu\'s items. When item_page_info.has_more is true, call get_menu again with item_page_info.next_cursor and repeat until has_more is false before treating the menu as complete.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { menu_id: { type: 'string' }, ...paginationInputSchema },
      required: ['menu_id'],
      outputSchema: {
        type: 'object',
        properties: { menu: menuObject, item_page_info: pageInfoObject },
        required: ['menu', 'item_page_info'],
      },
    }),
  siteTool({
      name: 'create_menu',
      description: 'Create a menu.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { name: { type: 'string' }, location_id: { type: 'string' }, description: { type: 'string' } },
      required: ['name'],
      outputSchema: menuMutationResultObject,
    }),
  siteTool({
      name: 'update_menu',
      description: 'Update a menu.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        menu_id: { type: 'string' },
        name: { type: 'string' },
        description: { type: 'string' },
        is_visible: { type: 'boolean' },
        section_order: { type: 'array', items: { type: 'string' }, description: 'Section names in display order.' },
      },
      required: ['menu_id'],
      outputSchema: menuMutationResultObject,
    }),
  siteTool({
      name: 'delete_menu',
      description: 'Delete a menu.',
      domain: 'menus',
      minimumRole: 'admin',
      confirmRequired: true,
      inputSchema: { menu_id: { type: 'string' } },
      required: ['menu_id'],
      outputSchema: {
        type: 'object',
        properties: { deleted: { type: 'boolean' } },
        required: ['deleted'],
      },
    }),
  siteTool({
      name: 'create_menu_item',
      description: 'Create a menu item.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      strict: true,
      inputSchema: {
        menu_id: { type: 'string' },
        section: { type: 'string', description: 'Required menu section name, for example Cocktails, Mains, or Desserts.' },
        name: { type: 'string' },
        description: { type: ['string', 'null'] },
        price_amount: { type: ['string', 'number', 'null'], description: 'Canonical price field for menu items.' },
        compare_at_price_amount: { type: ['string', 'number', 'null'], description: 'Regular/pre-sale price. Set alongside price_amount to run a sale.' },
        sale_starts_at: { type: ['string', 'null'], description: 'ISO 8601 date/time the sale becomes active. Optional.' },
        sale_ends_at: { type: ['string', 'null'], description: 'ISO 8601 date/time the sale ends. Optional.' },
        available: { type: 'boolean' },
        featured: { type: 'boolean' },
        featured_sort_order: { type: 'number' },
        sort_order: { type: 'number' },
        allergens: { type: 'array', items: { type: 'string' } },
        ingredients: { type: 'array', items: { type: 'string' } },
        dietary_notes: { type: 'array', items: { type: 'string' } },
        preparation: { type: ['string', 'null'] },
        serving_note: { type: ['string', 'null'] },
        media: {
          type: 'array',
          description: 'Ordered image/video media asset references. Position 0 is the cover everywhere. Videos in cover position must already have thumbnail_url/poster metadata.',
          maxItems: MAX_MENU_ITEM_MEDIA,
          uniqueItems: true,
          items: {
            type: 'object',
            properties: {
              asset_id: { type: 'string', description: 'Active image or video asset id from get_site_media_assets.' },
            },
            required: ['asset_id'],
            additionalProperties: false,
          },
        },
        ...seoOverrideFieldsSchema(),
      },
      required: ['menu_id', 'section', 'name'],
      outputSchema: menuItemMutationResultObject,
    }),
  siteTool({
      name: 'add_menu_items_batch',
      description: `Atomically add up to ${MAX_MENU_BATCH_ITEMS} brand-new menu items in one call. Use this when the user is adding new items, not revising existing ones. The complete request either commits or rolls back together.`,
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      strict: true,
      inputSchema: {
        menu_id: { type: 'string' },
        items: {
          type: 'array',
          description: `The complete set of new items to add atomically. Up to ${MAX_MENU_BATCH_ITEMS}.`,
          minItems: 1,
          maxItems: MAX_MENU_BATCH_ITEMS,
          items: {
            type: 'object',
            properties: {
              section: { type: 'string', description: 'Required menu section name, for example Cocktails, Mains, or Desserts.' },
              name: { type: 'string' },
              description: { type: ['string', 'null'] },
              price_amount: { type: ['string', 'number', 'null'], description: 'Canonical price field for menu items.' },
              compare_at_price_amount: { type: ['string', 'number', 'null'], description: 'Regular/pre-sale price. Set alongside price_amount to run a sale.' },
              sale_starts_at: { type: ['string', 'null'], description: 'ISO 8601 date/time the sale becomes active. Optional.' },
              sale_ends_at: { type: ['string', 'null'], description: 'ISO 8601 date/time the sale ends. Optional.' },
              available: { type: 'boolean' },
              featured: { type: 'boolean' },
              featured_sort_order: { type: 'number' },
              sort_order: { type: 'number' },
              allergens: { type: 'array', items: { type: 'string' } },
              ingredients: { type: 'array', items: { type: 'string' } },
              dietary_notes: { type: 'array', items: { type: 'string' } },
              preparation: { type: ['string', 'null'] },
              serving_note: { type: ['string', 'null'] },
              media: {
                type: 'array',
                description: 'Ordered image/video media asset references. Position 0 is the cover everywhere. Videos in cover position must already have thumbnail_url/poster metadata.',
                maxItems: MAX_MENU_ITEM_MEDIA,
                uniqueItems: true,
                items: {
                  type: 'object',
                  properties: {
                    asset_id: { type: 'string', description: 'Active image or video asset id from get_site_media_assets.' },
                  },
                  required: ['asset_id'],
                  additionalProperties: false,
                },
              },
            },
            required: ['section', 'name'],
            additionalProperties: false,
          },
        },
      },
      required: ['menu_id', 'items'],
      outputSchema: {
        type: 'object',
        properties: {
          added: { type: 'number' },
          created: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                section: { type: 'string' },
                price_amount: { type: ['string', 'number', 'null'] },
              },
              required: ['id', 'name', 'section'],
            },
          },
          skipped: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                name: { type: 'string' },
                reason: { type: 'string' },
                existing_item_id: { type: ['string', 'null'] },
              },
              required: ['name', 'reason'],
            },
          },
          menu_id: { type: 'string' },
        },
        required: ['added', 'created', 'skipped', 'menu_id'],
      },
    }),
  siteTool({
      name: 'sync_menu_items',
      description: `Atomically reconcile up to ${MAX_MENU_BATCH_ITEMS} menu items with an existing menu — use for updates, complete replacements, revised prices/descriptions, renamed items, or mixed create/update work. Items match by item_id first, then by normalized name/slug. Read every get_menu page first, then send the complete intended mutation in one call. The complete request either commits or rolls back together.`,
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      strict: true,
      inputSchema: {
        menu_id: { type: 'string' },
        items: {
          type: 'array',
          description: `The complete item set to reconcile atomically. Up to ${MAX_MENU_BATCH_ITEMS}.`,
          minItems: 1,
          maxItems: MAX_MENU_BATCH_ITEMS,
          items: {
            type: 'object',
            properties: {
              item_id: { type: 'string', description: 'Existing menu item ID when known.' },
              section: { type: 'string', description: 'Section/category name.' },
              name: { type: 'string' },
              description: { type: ['string', 'null'] },
              price_amount: { type: ['string', 'number', 'null'] },
              compare_at_price_amount: { type: ['string', 'number', 'null'] },
              sale_starts_at: { type: ['string', 'null'] },
              sale_ends_at: { type: ['string', 'null'] },
              available: { type: 'boolean' },
              allergens: { type: 'array', items: { type: 'string' } },
              ingredients: { type: 'array', items: { type: 'string' } },
              dietary_notes: { type: 'array', items: { type: 'string' } },
              preparation: { type: ['string', 'null'] },
              serving_note: { type: ['string', 'null'] },
            },
            additionalProperties: false,
          },
        },
        set_missing_unavailable: {
          type: 'boolean',
          description: `Only true when the user explicitly asks to remove, replace, hide, or make omitted items unavailable and this call contains the complete intended menu (up to ${MAX_MENU_BATCH_ITEMS} items).`,
        },
      },
      required: ['menu_id', 'items'],
      outputSchema: {
        type: 'object',
        properties: {
          menu_id: { type: 'string' },
          created: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                section: { type: 'string' },
                price_amount: { type: ['string', 'number', 'null'] },
              },
              required: ['id', 'name', 'section'],
            },
          },
          updated: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                section: { type: 'string' },
                price_amount: { type: ['string', 'number', 'null'] },
                available: { type: 'boolean' },
              },
              required: ['id', 'name', 'section', 'available'],
            },
          },
          unchanged: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
              },
              required: ['id', 'name'],
            },
          },
          made_unavailable: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
              },
              required: ['id', 'name'],
            },
          },
          skipped: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                name: { type: 'string' },
                reason: { type: 'string' },
                item_id: { type: 'string' },
              },
              required: ['name', 'reason'],
            },
          },
          summary: {
            type: 'object',
            properties: {
              created: { type: 'number' },
              updated: { type: 'number' },
              unchanged: { type: 'number' },
              made_unavailable: { type: 'number' },
              skipped: { type: 'number' },
            },
            required: ['created', 'updated', 'unchanged', 'made_unavailable', 'skipped'],
          },
        },
        required: ['menu_id', 'created', 'updated', 'unchanged', 'made_unavailable', 'skipped', 'summary'],
      },
    }),
  siteTool({
      name: 'update_menu_item',
      description: 'Update a menu item. To change its gallery photos, use attach_media/remove_media/reorder_media with {owner_type:"menu_item", owner_id:<menu_item_id>, slot:"gallery"} — this tool does not accept media.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      strict: true,
      inputSchema: {
        menu_item_id: { type: 'string' },
        section: { type: 'string' },
        name: { type: 'string' },
        description: { type: ['string', 'null'] },
        price_amount: { type: ['string', 'number', 'null'], description: 'Canonical price field for menu items.' },
        compare_at_price_amount: { type: ['string', 'number', 'null'], description: 'Regular/pre-sale price. Set alongside price_amount to run a sale.' },
        sale_starts_at: { type: ['string', 'null'], description: 'ISO 8601 date/time the sale becomes active. Optional.' },
        sale_ends_at: { type: ['string', 'null'], description: 'ISO 8601 date/time the sale ends. Optional.' },
        available: { type: 'boolean' },
        featured: { type: 'boolean' },
        featured_sort_order: { type: 'number' },
        sort_order: { type: 'number' },
        allergens: { type: 'array', items: { type: 'string' } },
        ingredients: { type: 'array', items: { type: 'string' } },
        dietary_notes: { type: 'array', items: { type: 'string' } },
        preparation: { type: ['string', 'null'] },
        serving_note: { type: ['string', 'null'] },
        ...seoOverrideFieldsSchema(),
      },
      required: ['menu_item_id'],
      outputSchema: menuItemMutationResultObject,
    }),
  siteTool({
      name: 'delete_menu_item',
      description: 'Delete a menu item.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { menu_item_id: { type: 'string' } },
      required: ['menu_item_id'],
      outputSchema: {
        type: 'object',
        properties: { deleted: { type: 'boolean' } },
        required: ['deleted'],
      },
    }),
  siteTool({
      name: 'rename_menu_section',
      description: 'Rename a menu section.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { menu_id: { type: 'string' }, old_name: { type: 'string' }, new_name: { type: 'string' } },
      required: ['menu_id', 'old_name', 'new_name'],
      outputSchema: {
        type: 'object',
        properties: {
          updated: { type: 'number', description: 'Number of items renamed.' },
        },
        required: ['updated'],
      },
    }),
  siteTool({
      name: 'delete_menu_section',
      description: 'Delete a menu section.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { menu_id: { type: 'string' }, section_name: { type: 'string' } },
      required: ['menu_id', 'section_name'],
      outputSchema: {
        type: 'object',
        properties: {
          deleted: { type: 'number', description: 'Number of items deleted.' },
        },
        required: ['deleted'],
      },
    }),
  siteTool({
      name: 'reorder_menu_items',
      description: 'Reorder menu items.',
      domain: 'menus',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { menu_id: { type: 'string' }, updates: { type: 'array' } },
      required: ['menu_id', 'updates'],
      outputSchema: {
        type: 'object',
        properties: { updated: { type: 'boolean' } },
        required: ['updated'],
      },
    }),
]
