import {organizationTool,type McpToolDefinition} from './shared'
const string={type:'string'} as const
const period={from:{...string,description:'Inclusive UTC ISO instant'},to:{...string,description:'Exclusive UTC ISO instant'}}
export const PAYMENTS_TOOLS:McpToolDefinition[]=[
 organizationTool({name:'get_payment_summary',description:'Report seller captured volume, refunds and disputes separately by currency in a UTC period. Trust receipts are not labeled earned revenue. Existing records remain serviceable after downgrade.',domain:'payments',minimumRole:'admin',confirmRequired:false,inputSchema:period,required:['from','to']}),
 organizationTool({name:'list_payments',description:'List tenant customer Payments with canonical payable links and currency minor amounts. Cursor pages seller records, never platform subscription transactions.',domain:'payments',minimumRole:'admin',confirmRequired:false,inputSchema:{...period,after:string},required:['from','to']}),
 organizationTool({name:'get_payment',description:'Read one seller Payment, immutable purchase snapshot, refund and dispute projections.',domain:'payments',minimumRole:'admin',confirmRequired:false,inputSchema:{payment_id:string},required:['payment_id']}),
 organizationTool({name:'get_payment_payouts',description:'Read connected Stripe balance and payouts with source and retrieval time. Does not transfer funds.',domain:'payments',minimumRole:'admin',confirmRequired:false}),
 organizationTool({name:'get_payments_usage',description:'Read Metronome Payments invoices, accrued usage and undelivered provider-cost events separately from Better Auth subscription billing.',domain:'payments',minimumRole:'admin',confirmRequired:false}),
 organizationTool({name:'request_payment_refund',description:'Prepare full or partial direct-charge refund for explicit authenticated browser approval. Returns a bound approval handoff; this request does not refund principal. Never treat model confirm=true as financial authorization.',domain:'payments',minimumRole:'admin',confirmRequired:true,inputSchema:{payment_id:string,amount:{type:'integer',minimum:1,description:'Refund principal in the Payment currency minor units'}},required:['payment_id','amount']}),
 organizationTool({name:'issue_payment_refund',description:'Execute a seller refund only with an unexpired authorization approved by this operator in the authenticated browser. A model cannot mint the authorization. Uses connected-account native refunds, stable idempotency and current refundable principal.',domain:'payments',minimumRole:'admin',confirmRequired:true,inputSchema:{authorization_id:string},required:['authorization_id']}),
 organizationTool({name:'create_payment_checkout',description:'Create Stripe-hosted one-time seller checkout for an active canonical Product/Variant. Booking checkout reserves durable capacity before Stripe. Operator checkout leaves buyer unclaimed; typed email never proves ownership. Physical fulfillment remains merchant-arranged.',domain:'payments',minimumRole:'admin',confirmRequired:true,requiredEntitlement:'payments',inputSchema:{product_id:string,variant_id:string,session_id:string,quantity:{type:'integer',minimum:1,maximum:100},idempotency_key:string},required:['product_id','variant_id','quantity','idempotency_key']}),
 organizationTool({name:'open_payments_onboarding',description:'Open authenticated merchant Stripe Payments integration management. Stripe-native onboarding collects KYC and bank details; never collect these in chat.',domain:'payments',minimumRole:'owner',confirmRequired:true}),
]
