import type { McpToolDefinition } from './shared'
import { postObject, siteTool } from './shared'
import { MEDIA_UPLOAD_WIDGET_RESOURCE_URI } from '~/server/utils/mcp-widgets'

export const POSTS_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'list_posts',
      description: 'List posts. Pass location_id to see only posts scoped to one location; omit to see all posts site-wide (including site-wide ones with no location).',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        status: { type: 'string' },
        location_id: { type: 'string', description: 'Filter to posts restricted to this location.' },
      },
      outputSchema: {
        type: 'object',
        properties: { posts: { type: 'array', items: postObject } },
        required: ['posts'],
      },
    }),
  siteTool({
      name: 'get_post',
      description: 'Get a post.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { post_id: { type: 'string' } },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post: postObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'create_post',
      description: 'Create and publish a post. Use post_type to create a promotion or event instead of a standard update: "offer" for a discount/special (pair with offer_coupon/offer_terms), "event" for a scheduled happening (pair with event_title/event_start/event_end), or "update" for general news. Defaults to "standard".',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        body: { type: 'string' },
        title: { type: 'string' },
        post_type: { type: 'string', enum: ['standard', 'offer', 'event', 'update'], description: 'Determines how the post is presented. "offer" = promotion, "event" = scheduled happening.' },
        location_id: { type: 'string', description: 'Restrict this post to a specific location. Omit to apply site-wide.' },
        cta_type: { type: 'string', description: 'Call-to-action type shown with the post, e.g. "book", "order", "learn_more".' },
        cta_url: { type: 'string', description: 'URL the call-to-action button links to.' },
        event_title: { type: 'string', description: 'Event name. Use with post_type "event".' },
        event_start: { type: 'string', description: 'Event start datetime (ISO 8601). Use with post_type "event".' },
        event_end: { type: 'string', description: 'Event end datetime (ISO 8601). Use with post_type "event".' },
        offer_coupon: { type: 'string', description: 'Coupon code for the promotion. Use with post_type "offer".' },
        offer_terms: { type: 'string', description: 'Terms and conditions for the promotion. Use with post_type "offer".' },
        scheduled_for: { type: 'string', description: 'If set, the post is scheduled to publish at this datetime (ISO 8601) instead of immediately.' },
      },
      required: ['body'],
      outputSchema: {
        type: 'object',
        properties: { post: postObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'update_post',
      description: 'Update a post, including converting it into a promotion or event via post_type. Only provided fields are changed.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        post_id: { type: 'string' },
        body: { type: 'string' },
        title: { type: 'string' },
        post_type: { type: 'string', enum: ['standard', 'offer', 'event', 'update'], description: 'Determines how the post is presented. "offer" = promotion, "event" = scheduled happening.' },
        location_id: { type: ['string', 'null'], description: 'Restrict this post to a specific location. Pass null to clear it.' },
        cta_type: { type: 'string', description: 'Call-to-action type shown with the post, e.g. "book", "order", "learn_more".' },
        cta_url: { type: 'string', description: 'URL the call-to-action button links to.' },
        event_title: { type: 'string', description: 'Event name. Use with post_type "event".' },
        event_start: { type: 'string', description: 'Event start datetime (ISO 8601). Use with post_type "event".' },
        event_end: { type: 'string', description: 'Event end datetime (ISO 8601). Use with post_type "event".' },
        offer_coupon: { type: 'string', description: 'Coupon code for the promotion. Use with post_type "offer".' },
        offer_terms: { type: 'string', description: 'Terms and conditions for the promotion. Use with post_type "offer".' },
        scheduled_for: { type: 'string', description: 'If set, the post is scheduled to publish at this datetime (ISO 8601) instead of immediately.' },
      },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post: postObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'set_post_image',
      description: 'Use this when the user wants to add or change the photo on a post or update. Call get_site_media_assets first to find an active image asset id, then pass it here with the target post_id.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        post_id: { type: 'string' },
        asset_id: { type: 'string', description: 'Active image asset id from get_site_media_assets.' },
      },
      required: ['post_id', 'asset_id'],
      outputSchema: {
        type: 'object',
        properties: { post: postObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'open_post_media_upload',
      description: 'Launches the inline media upload widget scoped to a specific post — image only for posts today. After the widget reports a completed upload, call set_post_image with the returned assetId and this post_id.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      uiResourceUri: MEDIA_UPLOAD_WIDGET_RESOURCE_URI,
      inputSchema: {
        post_id: { type: 'string' },
      },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: {
          launched: { type: 'boolean' },
          resourceUri: { type: 'string' },
          post_id: { type: 'string' },
        },
        required: ['launched', 'resourceUri', 'post_id'],
      },
    }),
  siteTool({
      name: 'publish_post',
      description: 'Publish a post to one or more channels. channels defaults to ["site"]. Pass ["site","facebook"] or ["site","instagram"] or all three to simultaneously publish to social — requires a connected Facebook Page (get_facebook_connection). Instagram additionally requires the post to have an image. targets is accepted as a deprecated alias for channels.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: {
        post_id: { type: 'string' },
        channels: { type: 'array', items: { type: 'string', enum: ['site', 'facebook', 'instagram', 'gmb'] }, description: 'Channels to publish to. Defaults to ["site"].' },
        targets: { type: 'array', items: { type: 'string', enum: ['site', 'facebook', 'instagram', 'gmb'] }, description: 'Deprecated alias for channels. Prefer channels.' },
      },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post: postObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'delete_post',
      description: 'Delete a post. Only owners and admins can delete posts.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { post_id: { type: 'string' } },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post_id: { type: 'string' }, deleted: { type: 'boolean' }, error: { type: 'string' } },
      },
    }),
]
