import type { McpToolDefinition } from './shared'
import { postMutationResultObject, postObject, postPublishResultObject, siteTool } from './shared'

export const POSTS_TOOLS: McpToolDefinition[] = [
  siteTool({
      name: 'list_posts',
      description: 'List posts. Pass location_id to see only posts scoped to one location; omit to see all posts site-wide (including site-wide ones with no location).',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        status: { type: 'string' },
        location_id: { type: 'string', description: 'Filter to posts restricted to this location.' },
      },
      outputSchema: {
        type: 'object',
        properties: { posts: { type: 'array', items: postObject } },
        required: ['posts'],
      },
    }),
  siteTool({
      name: 'get_post',
      description: 'Get a post.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: { post_id: { type: 'string' } },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post: postObject },
        required: ['post'],
      },
    }),
  siteTool({
      name: 'create_post',
      description: 'Create a post and publish it to the website immediately unless scheduled_for is provided. This does not publish to social channels; use publish_post with explicit channels for social publication. Use post_type "offer" for a discount/special (requires offer_coupon or offer_terms), "event" for a scheduled happening (requires event_start), or "update" for general news. Defaults to "standard".',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        body: { type: 'string' },
        title: { type: 'string' },
        slug: { type: 'string', description: 'Optional public URL slug. If omitted, KrabiClaw generates a stable unique slug.' },
        seo_title: { type: 'string', description: 'Optional SEO title for the public post page.' },
        seo_description: { type: 'string', description: 'Optional SEO/meta description for the public post page.' },
        og_image_asset_id: { type: 'string', description: 'Optional Open Graph image asset id. Defaults to the cover image when omitted.' },
        image_asset_id: { type: 'string', description: 'Optional active image asset id to use as the canonical post cover.' },
        gallery_media: {
          type: 'array',
          description: 'Optional ordered gallery media for the public post page. Use active media asset ids from get_site_media_assets or uploaded/generated media.',
          items: {
            type: 'object',
            properties: {
              media_asset_id: { type: 'string' },
              role: { type: 'string', enum: ['gallery', 'cover'] },
              caption: { type: 'string' },
              alt_text: { type: 'string' },
            },
            required: ['media_asset_id'],
          },
        },
        post_type: { type: 'string', enum: ['standard', 'offer', 'event', 'update'], description: 'Determines how the post is presented. "offer" = promotion, "event" = scheduled happening.' },
        location_id: { type: 'string', description: 'Restrict this post to a specific location. Omit to apply site-wide.' },
        cta_type: { type: 'string', description: 'Call-to-action type shown with the post, e.g. "book", "order", "learn_more".' },
        cta_url: { type: 'string', description: 'URL the call-to-action button links to.' },
        event_title: { type: 'string', description: 'Event name. Use with post_type "event".' },
        event_start: { type: 'string', description: 'Event start datetime (ISO 8601). Use with post_type "event".' },
        event_end: { type: 'string', description: 'Event end datetime (ISO 8601). Use with post_type "event".' },
        offer_coupon: { type: 'string', description: 'Coupon code for the promotion. Use with post_type "offer".' },
        offer_terms: { type: 'string', description: 'Terms and conditions for the promotion. Use with post_type "offer".' },
        scheduled_for: { type: 'string', description: 'If set, the post is scheduled to publish at this datetime (ISO 8601) instead of immediately.' },
      },
      required: ['body'],
      outputSchema: postMutationResultObject,
    }),
  siteTool({
      name: 'update_post',
      description: 'Update a post, including converting it into a promotion or event via post_type. Only provided fields are changed.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        post_id: { type: 'string' },
        body: { type: 'string' },
        title: { type: 'string' },
        slug: { type: ['string', 'null'], description: 'Public URL slug. Pass null or omit to keep the current slug; pass a string to change it.' },
        seo_title: { type: ['string', 'null'] },
        seo_description: { type: ['string', 'null'] },
        og_image_asset_id: { type: ['string', 'null'] },
        image_asset_id: { type: ['string', 'null'], description: 'Active image asset id for the canonical post cover. Pass null to clear it.' },
        gallery_media: {
          type: 'array',
          description: 'Replace the ordered public post gallery. Omit to leave unchanged.',
          items: {
            type: 'object',
            properties: {
              media_asset_id: { type: 'string' },
              role: { type: 'string', enum: ['gallery', 'cover'] },
              caption: { type: ['string', 'null'] },
              alt_text: { type: ['string', 'null'] },
            },
            required: ['media_asset_id'],
          },
        },
        post_type: { type: 'string', enum: ['standard', 'offer', 'event', 'update'], description: 'Determines how the post is presented. "offer" = promotion, "event" = scheduled happening.' },
        location_id: { type: ['string', 'null'], description: 'Restrict this post to a specific location. Pass null to clear it.' },
        cta_type: { type: 'string', description: 'Call-to-action type shown with the post, e.g. "book", "order", "learn_more".' },
        cta_url: { type: 'string', description: 'URL the call-to-action button links to.' },
        event_title: { type: 'string', description: 'Event name. Use with post_type "event".' },
        event_start: { type: 'string', description: 'Event start datetime (ISO 8601). Use with post_type "event".' },
        event_end: { type: 'string', description: 'Event end datetime (ISO 8601). Use with post_type "event".' },
        offer_coupon: { type: 'string', description: 'Coupon code for the promotion. Use with post_type "offer".' },
        offer_terms: { type: 'string', description: 'Terms and conditions for the promotion. Use with post_type "offer".' },
        scheduled_for: { type: 'string', description: 'If set, the post is scheduled to publish at this datetime (ISO 8601) instead of immediately.' },
      },
      required: ['post_id'],
      outputSchema: postMutationResultObject,
    }),
  siteTool({
      name: 'set_post_image',
      description: 'Use this when the user wants to add or change the photo on a post or update. Call get_site_media_assets first to find an active image asset id, then pass it here with the target post_id.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: false,
      inputSchema: {
        post_id: { type: 'string' },
        asset_id: { type: 'string', description: 'Active image asset id from get_site_media_assets.' },
      },
      required: ['post_id', 'asset_id'],
      outputSchema: postMutationResultObject,
    }),
  siteTool({
      name: 'publish_post',
      description: 'Publish a post to one or more channels. channels defaults to ["site"]. Pass ["site","facebook"] or ["site","instagram"] or all three to simultaneously publish to social — requires a connected Facebook Page (get_facebook_connection). Instagram additionally requires the post to have an image. targets is accepted as a deprecated alias for channels.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: {
        post_id: { type: 'string' },
        channels: { type: 'array', items: { type: 'string', enum: ['site', 'facebook', 'instagram', 'gmb'] }, description: 'Channels to publish to. Defaults to ["site"].' },
        targets: { type: 'array', items: { type: 'string', enum: ['site', 'facebook', 'instagram', 'gmb'] }, description: 'Deprecated alias for channels. Prefer channels.' },
      },
      required: ['post_id'],
      outputSchema: postPublishResultObject,
    }),
  siteTool({
      name: 'delete_post',
      description: 'Delete a post. Only owners and admins can delete posts.',
      domain: 'posts',
      minimumRole: 'editor',
      confirmRequired: true,
      inputSchema: { post_id: { type: 'string' } },
      required: ['post_id'],
      outputSchema: {
        type: 'object',
        properties: { post_id: { type: 'string' }, deleted: { type: 'boolean' }, error: { type: 'string' } },
      },
    }),
]
