#!/usr/bin/env node
/**
 * Kikuzuki seed generator — ephemeral model.
 *
 * Generates SQL, writes to /tmp, applies via wrangler, discards the file.
 * No seeds/kikuzuki.sql is ever committed to git.
 *
 * Usage:
 *   yarn seed:kikuzuki              # local D1 (default)
 *   yarn seed:kikuzuki:remote       # remote production D1
 *   yarn seed:kikuzuki:staging      # staging D1
 *   node scripts/generate-kikuzuki-seed.ts --stdout   # print SQL only, no apply
 */

import { execFileSync } from 'node:child_process'
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import {
  renderKikuzukiCoreSeedBlock,
  renderKikuzukiMediaBlock,
  renderKikuzukiMenuBlock,
  renderKikuzukiContentBlock,
  renderKikuzukiExperienceBlock,
  renderKikuzukiReviewsBlock,
  renderKikuzukiBillingBlock,
} from '../seed-definitions/kikuzuki.ts'

const isStdout = process.argv.includes('--stdout')
const isRemote = process.argv.includes('--remote')
const isStaging = process.argv.includes('--staging')
const isPreview = process.argv.includes('--preview')

const wranglerArgs = [
  'wrangler',
  'd1',
  'execute',
  'DB',
  ...(isStaging ? ['--env', 'staging'] : isPreview ? ['--env', 'preview'] : isRemote ? [] : ['--local']),
  ...((isRemote || isStaging || isPreview) ? ['--remote'] : []),
]

const sql = `-- Kikuzuki seed (generated — do not edit this file)
-- Ephemeral: written to /tmp and discarded after apply
-- Preview at: http://kikuzuki-krabi-thailand.localhost:3000
-- Production at: https://kikuzuki-krabi-thailand.krabiclaw.com

PRAGMA foreign_keys = ON;

-- Theme is shared platform data, not client-owned.
INSERT OR IGNORE INTO themes (id, name, slug, version, description, status)
VALUES ('saya-theme-v1', 'Saya', 'saya', '1.0.0', 'Restaurant website theme', 'active');

-- Cleanly replace the protected kikuzuki tenant rows.
-- DELETE order respects FK constraints.
DELETE FROM sites WHERE id = 'site-kikuzuki' OR subdomain = 'kikuzuki-krabi-thailand';
DELETE FROM organization WHERE id = 'org-kikuzuki';
DELETE FROM site_domains WHERE domain IN ('kikuzuki-krabi-thailand.localhost', 'kikuzuki-krabi-thailand.krabiclaw.com');

-- Organization (owned by the dedicated Kikuzuki owner account)
INSERT INTO organization (id, name, slug, createdAt)
VALUES ('org-kikuzuki', 'Kikuzuki Krabi Thailand', 'kikuzuki-krabi-thailand', unixepoch());

-- Ensure the dedicated owner user exists to satisfy FK constraints.
INSERT OR IGNORE INTO user (id, name, email, emailVerified)
VALUES
  ('user-kikuzuki', 'Kikuzuki Owner', 'contact@kikuzuki.com', 1);

INSERT OR REPLACE INTO member (id, organizationId, userId, role, createdAt)
VALUES
  ('member-kikuzuki', 'org-kikuzuki', 'user-kikuzuki', 'owner', unixepoch());

${renderKikuzukiCoreSeedBlock()}

${renderKikuzukiMediaBlock()}

${renderKikuzukiMenuBlock()}

${renderKikuzukiContentBlock()}

${renderKikuzukiExperienceBlock()}

${renderKikuzukiReviewsBlock()}

${renderKikuzukiBillingBlock()}
`

if (isStdout) {
  process.stdout.write(sql)
  process.exit(0)
}

if (isRemote || isStaging || isPreview) {
  const checkOutput = execFileSync('npx', [
    ...wranglerArgs,
    '--command', "SELECT organization_id FROM sites WHERE id = 'site-kikuzuki'",
    '--json',
  ], { encoding: 'utf8' })
  const currentOrgId = JSON.parse(checkOutput)?.[0]?.results?.[0]?.organization_id

  if (currentOrgId && currentOrgId !== 'org-kikuzuki') {
    console.error(
      `[seed:kikuzuki] Refusing to reseed: site-kikuzuki is owned by "${currentOrgId}", not the demo org "org-kikuzuki".\n` +
      'This tenant has already been transferred to a real client. Reseeding would delete their live site, ' +
      'business_locations, site_content, media_assets, and custom domain rows, then recreate it back under the demo org.\n' +
      'Aborting.'
    )
    process.exit(1)
  }
}

const dir = mkdtempSync(join(tmpdir(), 'krabiclaw-seed-kikuzuki-'))
const sqlPath = join(dir, 'kikuzuki.sql')

try {
  writeFileSync(sqlPath, sql, 'utf8')

  const cmd = ['npx', ...wranglerArgs, '--file', sqlPath]
  console.log(`[seed:kikuzuki] Applying: ${cmd.join(' ')}`)
  execFileSync('npx', [...wranglerArgs, '--file', sqlPath], { stdio: 'inherit' })
  console.log('[seed:kikuzuki] Done.')
} finally {
  rmSync(dir, { recursive: true, force: true })
}
