#!/usr/bin/env node
/**
 * Kikuzuki seed generator — ephemeral model.
 *
 * Generates SQL, writes to /tmp, applies via wrangler, discards the file.
 * No seeds/kikuzuki.sql is ever committed to git.
 *
 * Usage:
 *   yarn seed:kikuzuki              # local D1 (default)
 *   yarn seed:kikuzuki:preview      # preview D1
 *   node scripts/generate-kikuzuki-seed.ts --stdout   # print SQL only, no apply
 */

import { execFileSync } from 'node:child_process'
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import {
  renderKikuzukiCoreSeedBlock,
  renderKikuzukiMediaBlock,
  renderKikuzukiProductsBlock,
  renderKikuzukiContentBlock,
  renderKikuzukiExperienceBlock,
  renderKikuzukiReviewsBlock,
  renderKikuzukiBillingBlock,
} from '../seed-definitions/kikuzuki.ts'

const wranglerCli = resolve('node_modules/wrangler/bin/wrangler.js')

// INCIDENT: Anthropic's Claude (an AI coding assistant) ran this script with
// --preview believing it was a harmless dry run. It is not. --preview
// executes these queries for real against the remote preview D1 database via
// `wrangler d1 execute DB --env preview --remote`. Claude did not check what
// the flag actually did before running it and fired a live remote write
// without asking the user first. That was Claude's mistake, not a tooling
// ambiguity — the behavior is spelled out a few lines below. If you are
// Claude (or any other AI assistant) reading this: check what a flag on a
// database-touching script actually does before you run it. Use --stdout to
// see the generated SQL without applying it anywhere.
const isStdout = process.argv.includes('--stdout')
const isPreview = process.argv.includes('--preview')

if (process.argv.includes('--remote') || process.argv.includes('--staging')) {
  console.error('This seed supports only local and preview databases.')
  process.exit(1)
}

const wranglerArgs = [
  'd1',
  'execute',
  'DB',
  ...(isPreview ? ['--env', 'preview', '--remote'] : ['--local']),
]

const SQL_HEADER = `-- Kikuzuki seed (generated — do not edit this file)
-- Ephemeral: written to /tmp and discarded after apply
-- Preview at: http://kikuzuki-krabi-thailand.localhost:3000
-- Production at: https://www.kikuzuki-thailand.com

PRAGMA foreign_keys = ON;
`

// Keep the largest curated seed in bounded imports instead of one oversized
// D1 file execution. Each chunk is applied exactly once; there is no retry or
// fallback path.
// Order matters: core creates the site/organization rows every later chunk
// has an FK dependency on.
const sqlChunks: { label: string; sql: string }[] = [
  {
    label: 'setup',
    sql: `${SQL_HEADER}
-- Theme is shared platform data, not client-owned.
INSERT OR IGNORE INTO themes (id, name, slug, version, description, status)
VALUES ('saya-theme-v1', 'Saya', 'saya', '1.0.0', 'Restaurant website theme', 'active');

-- Cleanly replace the protected kikuzuki tenant rows.
-- DELETE order respects FK constraints.
DELETE FROM sites WHERE id = 'site-kikuzuki' OR subdomain = 'kikuzuki-krabi-thailand';
DELETE FROM organization WHERE id = 'org-kikuzuki';
DELETE FROM site_domains WHERE domain IN ('kikuzuki-krabi-thailand.localhost', 'kikuzuki-krabi-thailand.krabiclaw.com', 'www.kikuzuki-thailand.com', 'kikuzuki-thailand.com');

-- Organization (owned by the dedicated Kikuzuki owner account)
INSERT INTO organization (id, name, slug, createdAt)
VALUES ('org-kikuzuki', 'Kikuzuki Krabi Thailand', 'kikuzuki-krabi-thailand', unixepoch());

-- Ensure the dedicated owner user exists to satisfy FK constraints.
INSERT OR IGNORE INTO user (id, name, email, emailVerified)
VALUES
  ('user-kikuzuki', 'Kikuzuki Owner', 'owner@kikuzuki.example', 1);

INSERT OR REPLACE INTO member (id, organizationId, userId, role, createdAt)
VALUES
  ('member-kikuzuki', 'org-kikuzuki', 'user-kikuzuki', 'owner', unixepoch());
`,
  },
  { label: 'core', sql: `${SQL_HEADER}\n${renderKikuzukiCoreSeedBlock()}\n` },
  { label: 'media', sql: `${SQL_HEADER}\n${renderKikuzukiMediaBlock()}\n` },
  { label: 'products', sql: `${SQL_HEADER}\n${renderKikuzukiProductsBlock()}\n` },
  { label: 'content', sql: `${SQL_HEADER}\n${renderKikuzukiContentBlock()}\n` },
  { label: 'experience', sql: `${SQL_HEADER}\n${renderKikuzukiExperienceBlock()}\n` },
  { label: 'reviews', sql: `${SQL_HEADER}\n${renderKikuzukiReviewsBlock()}\n` },
  { label: 'billing', sql: `${SQL_HEADER}\n${renderKikuzukiBillingBlock()}\n` },
]

if (isStdout) {
  await new Promise<void>((resolve, reject) => {
    process.stdout.write(sqlChunks.map((c) => c.sql).join('\n'), error => error ? reject(error) : resolve())
  })
  process.exit(0)
}

if (isPreview) {
  const checkOutput = execFileSync(process.execPath, [wranglerCli,
    ...wranglerArgs,
    '--command', "SELECT organization_id FROM sites WHERE id = 'site-kikuzuki'",
    '--json',
  ], { encoding: 'utf8' })
  const currentOrgId = JSON.parse(checkOutput)?.[0]?.results?.[0]?.organization_id

  if (currentOrgId && currentOrgId !== 'org-kikuzuki') {
    console.error(
      `[seed:kikuzuki] Refusing to reseed: site-kikuzuki is owned by "${currentOrgId}", not the demo org "org-kikuzuki".\n` +
      'This tenant has already been transferred to a real client. Reseeding would delete their live site, ' +
      'business_locations, tenant pages, media_assets, and custom domain rows, then recreate it back under the demo org.\n' +
      'Aborting.'
    )
    process.exit(1)
  }
}

const dir = mkdtempSync(join(tmpdir(), 'krabiclaw-seed-kikuzuki-'))

try {
  for (const chunk of sqlChunks) {
    const sqlPath = join(dir, `kikuzuki-${chunk.label}.sql`)
    writeFileSync(sqlPath, chunk.sql, 'utf8')

    const cmd = ['wrangler', ...wranglerArgs, '--file', sqlPath]
    console.log(`[seed:kikuzuki:${chunk.label}] Applying: ${cmd.join(' ')}`)
    execFileSync(process.execPath, [wranglerCli, ...wranglerArgs, '--file', sqlPath], { stdio: 'inherit' })
  }
  console.log('[seed:kikuzuki] Done.')
} finally {
  rmSync(dir, { recursive: true, force: true })
}
