import { sql } from "drizzle-orm"
import { sqliteTable, integer, text, numeric, real } from "drizzle-orm/sqlite-core"
import type { AnySQLiteColumn } from "drizzle-orm/sqlite-core"

export const account = sqliteTable("account", {
	id: text().primaryKey(),
	accountId: text().notNull(),
	providerId: text().notNull(),
	userId: text().notNull().references(() => user.id, { onDelete: "cascade" } ),
	accessToken: text(),
	refreshToken: text(),
	idToken: text(),
	expiresAt: integer({ mode: "timestamp" }),
	accessTokenExpiresAt: integer({ mode: "timestamp" }),
	refreshTokenExpiresAt: integer({ mode: "timestamp" }),
	scope: text(),
	password: text(),
	createdAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
	updatedAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const ai_credits = sqliteTable("ai_credits", {
	organization_id: text().primaryKey().references(() => organization.id, { onDelete: "cascade" } ),
	balance: integer().default(0).notNull(),
	lifetime_used: integer().default(0).notNull(),
	last_topped_up_at: text(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const ai_usage_log = sqliteTable("ai_usage_log", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().references(() => sites.id, { onDelete: "set null" } ),
	action: text().notNull(),
	model: text().notNull(),
	input_tokens: integer().default(0).notNull(),
	output_tokens: integer().default(0).notNull(),
	credits_charged: integer().default(0).notNull(),
	cf_gateway_log_id: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const business_location_translations = sqliteTable("business_location_translations", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().notNull().references(() => business_locations.id, { onDelete: "cascade" } ),
	locale: text().notNull(),
	title: text(),
	address: text(),
	city: text(),
	description: text(),
	short_description: text(),
	status: text().default("draft").notNull(),
	source_hash: text(),
	translated_at: text(),
	reviewed_at: text(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_by: text(),
});

export const business_locations = sqliteTable("business_locations", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	slug: text().notNull(),
	google_location_id: text(),
	google_connection_id: text().references((): AnySQLiteColumn => google_business_connections.id, { onDelete: "set null" } ),
	title: text().notNull(),
	address: text(),
	city: text(),
	neighborhood: text(),
	phone: text(),
	website_url: text(),
	maps_url: text(),
	latitude: real(),
	longitude: real(),
	opening_hours: text(),
	categories: text(),
	rating: real(),
	review_count: integer(),
	is_primary: numeric(),
	status: text().default("active"),
	last_synced_at: text(),
	description: text(),
	short_description: text(),
	description_provenance: text(),
	special_hours: text(),
	price_level: text(),
	attributes: text(),
	email: text(),
	facebook_url: text(),
	facebook_page_id: text(),
	facebook_connection_id: text().references(() => facebook_pages_connections.id, { onDelete: "set null" } ),
	instagram_url: text(),
	tiktok_url: text(),
	grab_url: text(),
	uber_eats_url: text(),
	foodpanda_url: text(),
	google_place_id: text(),
	hero_image_asset_id: text().references(() => media_assets_old.id, { onDelete: "set null" } ),
	hero_video_asset_id: text().references(() => media_assets_old.id, { onDelete: "set null" } ),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	notification_phone: text(),
	timezone: text(),
});

export const canary_runs = sqliteTable("canary_runs", {
	id: text().primaryKey(),
	run_type: text().notNull(),
	environment: text().default("production").notNull(),
	status: text().notNull(),
	organization_id: text().references(() => organization.id, { onDelete: "set null" } ),
	site_id: text().references(() => sites.id, { onDelete: "set null" } ),
	details_json: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const chowbot_channel_state = sqliteTable("chowbot_channel_state", {
	user_id: text().notNull().references(() => user.id, { onDelete: "cascade" } ),
	channel: text().notNull(),
	selected_site_id: text().references(() => sites.id, { onDelete: "set null" } ),
	active_conversation_id: text().references(() => chowbot_conversations.id, { onDelete: "set null" } ),
	pending_media: text(),
	pending_confirmation: text(),
	last_inbound_id: text(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const chowbot_conversations = sqliteTable("chowbot_conversations", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	user_id: text().notNull().references(() => user.id, { onDelete: "cascade" } ),
	title: text().default("New Conversation").notNull(),
	active_channel: text().default("dashboard").notNull(),
	status: text().default("active").notNull(),
	selected_location_id: text().references(() => business_locations.id, { onDelete: "set null" } ),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const chowbot_messages = sqliteTable("chowbot_messages", {
	id: text().primaryKey(),
	conversation_id: text().notNull().references(() => chowbot_conversations.id, { onDelete: "cascade" } ),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	user_id: text().references(() => user.id, { onDelete: "set null" } ),
	role: text().notNull(),
	channel: text().notNull(),
	content: text(),
	media: text(),
	meta_message_id: text(),
	tool_calls: text(),
	status: text().default("sent").notNull(),
	error: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const contact_submissions = sqliteTable("contact_submissions", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	name: text().notNull(),
	email: text().notNull(),
	message: text().notNull(),
	status: text().default("new").notNull(),
	ip_hash: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const dashboard_preferences = sqliteTable("dashboard_preferences", {
	id: text().primaryKey(),
	user_id: text().notNull().references(() => user.id, { onDelete: "cascade" } ),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	selected_location_id: text().references(() => business_locations.id, { onDelete: "set null" } ),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
});

export const domain_reconciliation_jobs = sqliteTable("domain_reconciliation_jobs", {
	id: text().primaryKey(),
	domain_id: text().notNull().references(() => site_domains.id, { onDelete: "cascade" } ),
	status: text().default("queued").notNull(),
	run_after: text().notNull(),
	attempts: integer().default(0).notNull(),
	last_error: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
});

export const experience_bookings = sqliteTable("experience_bookings", {
	id: text().primaryKey(),
	experience_id: text().notNull().references(() => experiences.id, { onDelete: "cascade" } ),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	guest_name: text().notNull(),
	guest_email: text().notNull(),
	guest_phone: text(),
	party_size: integer().default(1).notNull(),
	booking_date: text().notNull(),
	time_slot: text().notNull(),
	status: text().default("pending").notNull(),
	notes: text(),
	ip_hash: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const experience_slot_overrides = sqliteTable("experience_slot_overrides", {
	id: text().primaryKey(),
	experience_id: text().notNull().references(() => experiences.id, { onDelete: "cascade" } ),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	override_date: text().notNull(),
	time_slot: text().notNull(),
	status: text().default("closed").notNull(),
	capacity_override: integer(),
	note: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	created_by: text(),
});

export const facebook_pages_connections = sqliteTable("facebook_pages_connections", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	connected_by_user_id: text().references(() => user.id, { onDelete: "set null" } ),
	facebook_user_id: text().notNull(),
	facebook_page_id: text(),
	facebook_page_name: text(),
	encrypted_user_token: text().notNull(),
	encrypted_page_token: text(),
	user_token_expires_at: text(),
	scopes: text(),
	status: text().default("active").notNull(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const google_business_connections = sqliteTable("google_business_connections", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().references((): AnySQLiteColumn => business_locations.id, { onDelete: "set null" } ),
	connected_by_user_id: text().references(() => user.id, { onDelete: "set null" } ),
	provider_account_email: text().notNull(),
	encrypted_access_token: text(),
	encrypted_refresh_token: text().notNull(),
	scopes: text().notNull(),
	expires_at: text(),
	status: text().default("active").notNull(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const google_business_events = sqliteTable("google_business_events", {
	id: text().primaryKey(),
	organization_id: text().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().references(() => sites.id, { onDelete: "cascade" } ),
	google_location_id: text(),
	event_type: text(),
	payload: text(),
	status: text().default("pending"),
	error: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const google_place_snapshots = sqliteTable("google_place_snapshots", {
	id: text().primaryKey(),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().references(() => business_locations.id, { onDelete: "set null" } ),
	place_id: text().notNull(),
	source_url: text(),
	snapshot_json: text().notNull(),
	fetched_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const invitation = sqliteTable("invitation", {
	id: text().primaryKey(),
	organizationId: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	email: text().notNull(),
	role: text(),
	status: text().default("pending").notNull(),
	expiresAt: integer({ mode: "timestamp" }).notNull(),
	inviterId: text().notNull().references(() => user.id, { onDelete: "cascade" } ),
	createdAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const jwks = sqliteTable("jwks", {
	id: text().primaryKey(),
	publicKey: text().notNull(),
	privateKey: text().notNull(),
	alg: text(),
	crv: text(),
	createdAt: integer({ mode: "timestamp" }).notNull(),
	expiresAt: integer({ mode: "timestamp" }),
});

export const location_qa = sqliteTable("location_qa", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().notNull().references(() => business_locations.id, { onDelete: "cascade" } ),
	google_question_id: text(),
	question: text().notNull(),
	question_author: text(),
	question_date: text(),
	answer: text(),
	answer_author: text(),
	answer_date: text(),
	is_owner_answer: integer().default(0).notNull(),
	upvote_count: integer().default(0).notNull(),
	source: text().default("manual").notNull(),
	status: text().default("published").notNull(),
	sort_order: integer().default(0).notNull(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const media_assets = sqliteTable("media_assets", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references((): AnySQLiteColumn => sites.id, { onDelete: "cascade" } ),
	location_id: text().references(() => business_locations.id, { onDelete: "set null" } ),
	kind: text().notNull(),
	provider: text().notNull(),
	source: text().notNull(),
	cloudflare_image_id: text(),
	r2_key: text(),
	google_media_name: text(),
	public_url: text(),
	thumbnail_url: text(),
	mime_type: text(),
	file_name: text(),
	file_size: integer(),
	width: integer(),
	height: integer(),
	duration: integer(),
	alt_text: text(),
	category: text(),
	status: text().default("active").notNull(),
	created_by_user_id: text().references(() => user.id, { onDelete: "set null" } ),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	delete_pending_at: text(),
});

export const media_assets_old = sqliteTable("media_assets_old", {
	id: text().primaryKey(),
	organization_id: text().notNull(),
	site_id: text().notNull(),
	location_id: text(),
	kind: text().notNull(),
	provider: text().notNull(),
	source: text().notNull(),
	cloudflare_image_id: text(),
	r2_key: text(),
	google_media_name: text(),
	public_url: text(),
	thumbnail_url: text(),
	mime_type: text(),
	file_name: text(),
	file_size: integer(),
	width: integer(),
	height: integer(),
	duration: integer(),
	alt_text: text(),
	category: text(),
	status: text().default("active").notNull(),
	created_by_user_id: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const member = sqliteTable("member", {
	id: text().primaryKey(),
	organizationId: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	userId: text().notNull().references(() => user.id, { onDelete: "cascade" } ),
	role: text().default("member").notNull(),
	createdAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const menu_item_translations = sqliteTable("menu_item_translations", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	menu_item_id: text().notNull().references(() => menu_items.id, { onDelete: "cascade" } ),
	locale: text().notNull(),
	section: text(),
	name: text(),
	description: text(),
	allergens: text(),
	ingredients: text(),
	dietary_notes: text(),
	preparation: text(),
	serving_note: text(),
	status: text().default("draft").notNull(),
	source_hash: text(),
	translated_at: text(),
	reviewed_at: text(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_by: text(),
});

export const menu_items = sqliteTable("menu_items", {
	id: text().primaryKey(),
	menu_id: text().notNull().references(() => menus.id, { onDelete: "cascade" } ),
	section: text().notNull(),
	name: text().notNull(),
	slug: text().default("").notNull(),
	description: text(),
	price_amount: numeric(),
	image_asset_id: text().references(() => media_assets_old.id, { onDelete: "set null" } ),
	available: numeric().default(sql`1`).notNull(),
	featured: numeric().notNull(),
	featured_sort_order: integer().default(0).notNull(),
	sort_order: integer().default(0).notNull(),
	allergens: text(),
	ingredients: text(),
	dietary_notes: text(),
	preparation: text(),
	serving_note: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	created_by: text(),
	updated_by: text(),
});

export const menu_translations = sqliteTable("menu_translations", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	menu_id: text().notNull().references(() => menus.id, { onDelete: "cascade" } ),
	locale: text().notNull(),
	name: text(),
	description: text(),
	section_order: text(),
	status: text().default("draft").notNull(),
	source_hash: text(),
	translated_at: text(),
	reviewed_at: text(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_by: text(),
});

export const menus = sqliteTable("menus", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().references(() => business_locations.id, { onDelete: "cascade" } ),
	name: text().notNull(),
	description: text(),
	status: text().default("draft").notNull(),
	section_order: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	created_by: text(),
	updated_by: text(),
});

export const notifications = sqliteTable("notifications", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().references(() => sites.id, { onDelete: "set null" } ),
	channel: text().default("dashboard").notNull(),
	template: text().notNull(),
	recipient: text(),
	title: text(),
	payload: text(),
	status: text().default("pending").notNull(),
	provider_message_id: text(),
	error: text(),
	read_at: text(),
	sent_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const oauthAccessToken = sqliteTable("oauthAccessToken", {
	id: text().primaryKey(),
	clientId: text().notNull(),
	userId: text(),
	token: text().notNull(),
	scopes: text().default("").notNull(),
	expiresAt: integer({ mode: "timestamp" }).notNull(),
	createdAt: integer({ mode: "timestamp" }).notNull(),
	sessionId: text(),
	referenceId: text(),
	refreshId: text(),
});

export const oauthClient = sqliteTable("oauthClient", {
	id: text().primaryKey(),
	clientId: text().notNull(),
	clientSecret: text(),
	name: text().notNull(),
	redirectUris: text().notNull(),
	scopes: text().default("").notNull(),
	public: integer().default(0).notNull(),
	requirePkce: integer().default(1).notNull(),
	skipConsent: integer().default(0).notNull(),
	userId: text(),
	metadata: text(),
	disabled: integer().default(0).notNull(),
	createdAt: integer({ mode: "timestamp" }).notNull(),
	updatedAt: integer({ mode: "timestamp" }).notNull(),
	enableEndSession: integer(),
	subjectType: text(),
	uri: text(),
	icon: text(),
	contacts: text(),
	tos: text(),
	policy: text(),
	softwareId: text(),
	softwareVersion: text(),
	softwareStatement: text(),
	postLogoutRedirectUris: text(),
	tokenEndpointAuthMethod: text(),
	grantTypes: text(),
	responseTypes: text(),
	type: text(),
	referenceId: text(),
});

export const oauthConsent = sqliteTable("oauthConsent", {
	id: text().primaryKey(),
	clientId: text().notNull(),
	userId: text().notNull(),
	scopes: text().default("").notNull(),
	createdAt: integer({ mode: "timestamp" }).notNull(),
	updatedAt: integer({ mode: "timestamp" }).notNull(),
	referenceId: text(),
});

export const oauthRefreshToken = sqliteTable("oauthRefreshToken", {
	id: text().primaryKey(),
	clientId: text().notNull(),
	userId: text(),
	token: text().notNull(),
	scopes: text().default("").notNull(),
	accessTokenId: text(),
	expiresAt: integer({ mode: "timestamp" }).notNull(),
	createdAt: integer({ mode: "timestamp" }).notNull(),
	sessionId: text(),
	referenceId: text(),
	revoked: integer({ mode: "timestamp" }),
	authTime: integer({ mode: "timestamp" }),
});

export const organization = sqliteTable("organization", {
	id: text().primaryKey(),
	name: text().notNull(),
	slug: text(),
	logo: text(),
	metadata: text(),
	createdAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const organization_billing = sqliteTable("organization_billing", {
	id: text(),
	organization_id: text().primaryKey().references(() => organization.id, { onDelete: "cascade" } ),
	stripe_customer_id: text(),
	stripe_subscription_id: text(),
	stripe_subscription_item_id: text(),
	status: text().default("free").notNull(),
	plan: text().default("free").notNull(),
	current_period_end: text(),
	cancel_at_period_end: numeric(),
	auto_topup_enabled: integer().default(0).notNull(),
	auto_topup_bundle: integer().default(500).notNull(),
	auto_topup_threshold: integer().default(100).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const organization_entitlements = sqliteTable("organization_entitlements", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	key: text().notNull(),
	value: text(),
	source: text().default("system").notNull(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const platform_analytics = sqliteTable("platform_analytics", {
	id: text().primaryKey(),
	metric: text().notNull(),
	value: integer().notNull(),
	date: text().notNull(),
});

export const platform_blog_posts = sqliteTable("platform_blog_posts", {
	id: text().primaryKey(),
	title: text().notNull(),
	slug: text().notNull(),
	body: text().notNull(),
	excerpt: text(),
	category: text(),
	author_id: text().references(() => user.id, { onDelete: "set null" } ),
	featured_image_asset_id: text().references(() => media_assets_old.id, { onDelete: "set null" } ),
	published_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	seo_description: text(),
	seo_keywords: text(),
	canonical_url: text(),
	robots: text(),
});

export const platform_contact_submissions = sqliteTable("platform_contact_submissions", {
	id: text().primaryKey(),
	name: text().notNull(),
	email: text().notNull(),
	message: text().notNull(),
	status: text().default("new").notNull(),
	ip_hash: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const platform_content = sqliteTable("platform_content", {
	id: text().primaryKey(),
	page: text().notNull(),
	content: text().notNull(),
	updated_by: text().references(() => user.id, { onDelete: "set null" } ),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const platform_docs = sqliteTable("platform_docs", {
	id: text().primaryKey(),
	title: text().notNull(),
	slug: text().notNull(),
	body: text().notNull(),
	excerpt: text(),
	category: text(),
	author_id: text().references(() => user.id, { onDelete: "set null" } ),
	seo_description: text(),
	seo_keywords: text(),
	featured_image_asset_id: text().references(() => media_assets_old.id, { onDelete: "set null" } ),
	sort_order: integer().default(0),
	parent_doc_id: text(),
	difficulty_level: text(),
	status: text().default("draft").notNull(),
	published_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	canonical_url: text(),
	robots: text(),
});

export const post_channel_jobs = sqliteTable("post_channel_jobs", {
	id: text().primaryKey(),
	post_id: text().notNull().references(() => posts.id, { onDelete: "cascade" } ),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	channel: text().notNull(),
	status: text().default("pending").notNull(),
	provider_post_id: text(),
	error: text(),
	published_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const post_translations = sqliteTable("post_translations", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	post_id: text().notNull().references(() => posts.id, { onDelete: "cascade" } ),
	locale: text().notNull(),
	title: text(),
	body: text(),
	event_title: text(),
	offer_terms: text(),
	status: text().default("draft").notNull(),
	source_hash: text(),
	translated_at: text(),
	reviewed_at: text(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_by: text(),
});

export const posts = sqliteTable("posts", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().references(() => business_locations.id, { onDelete: "set null" } ),
	google_post_id: text(),
	post_type: text().default("standard").notNull(),
	title: text(),
	body: text().notNull(),
	image_asset_id: text().references(() => media_assets_old.id, { onDelete: "set null" } ),
	cta_type: text(),
	cta_url: text(),
	event_title: text(),
	event_start: text(),
	event_end: text(),
	offer_coupon: text(),
	offer_terms: text(),
	status: text().default("draft").notNull(),
	scheduled_for: text(),
	published_at: text(),
	created_by: text().notNull(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const rate_limits = sqliteTable("rate_limits", {
	key: text().primaryKey(),
	count: integer().default(0).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	expires_at: text(),
});

export const reservation_submissions = sqliteTable("reservation_submissions", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().notNull().references(() => business_locations.id, { onDelete: "cascade" } ),
	name: text().notNull(),
	email: text().notNull(),
	phone: text().notNull(),
	date: text().notNull(),
	time: text().notNull(),
	guests: text().notNull(),
	requests: text(),
	status: text().default("new").notNull(),
	ip_hash: text(),
	cancellation_token_hash: text(),
	cancellation_token_expires_at: text(),
	cancellation_token_used_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const reviews = sqliteTable("reviews", {
	id: text().primaryKey(),
	organization_id: text().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().references(() => business_locations.id, { onDelete: "cascade" } ),
	menu_item_slug: text(),
	author_name: text(),
	reviewer_photo_url: text(),
	rating: integer().notNull(),
	title: text(),
	content: text(),
	google_review_id: text(),
	owner_reply: text(),
	owner_reply_at: text(),
	photo_urls: text(),
	helpful_count: integer().default(0),
	status: text().default("pending"),
	source: text().default("direct"),
	ip_hash: text(),
	user_agent: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
});

export const service_addon_purchases = sqliteTable("service_addon_purchases", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	addon_type: text().notNull(),
	stripe_payment_intent_id: text(),
	fulfilled_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const session = sqliteTable("session", {
	id: text().primaryKey(),
	expiresAt: integer({ mode: "timestamp" }).notNull(),
	token: text().notNull(),
	createdAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
	updatedAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
	ipAddress: text(),
	userAgent: text(),
	activeOrganizationId: text(),
	activeTeamId: text(),
	impersonatedBy: text(),
	userId: text().notNull().references(() => user.id, { onDelete: "cascade" } ),
});

export const site_analytics_daily = sqliteTable("site_analytics_daily", {
	id: text().primaryKey(),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	date: text().notNull(),
	page_views: integer().default(0),
	unique_sessions: integer().default(0),
	avg_session_duration: integer().default(0),
	top_pages: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	unique_visitors: integer().default(0),
	pages_per_session: real(),
	returning_visitors: integer().default(0),
});

export const site_billing = sqliteTable("site_billing", {
	id: text().primaryKey(),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	stripe_subscription_id: text(),
	stripe_subscription_item_id: text(),
	plan: text().default("free").notNull(),
	status: text().default("free").notNull(),
	current_period_end: text(),
	cancel_at_period_end: numeric(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	stripe_customer_id: text(),
	payment_method: text().default("stripe").notNull(),
	local_rate: integer(),
	local_currency: text(),
	last_reminder_sent_at: text(),
});

export const site_config = sqliteTable("site_config", {
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	key: text().notNull(),
	value: text(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const site_content = sqliteTable("site_content", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().references(() => business_locations.id, { onDelete: "cascade" } ),
	page: text().notNull(),
	field: text().notNull(),
	content: text(),
	hero_title: text(),
	hero_subtitle: text(),
	hero_image_asset_id: text().references(() => media_assets_old.id, { onDelete: "set null" } ),
	hero_video_asset_id: text().references(() => media_assets_old.id, { onDelete: "set null" } ),
	value: text(),
	type: text().default("text").notNull(),
	source: text().default("manual").notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_by: text(),
	component: text(),
});

export const site_content_translations = sqliteTable("site_content_translations", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().references(() => business_locations.id, { onDelete: "cascade" } ),
	locale: text().notNull(),
	page: text().notNull(),
	field: text().notNull(),
	content: text(),
	hero_title: text(),
	hero_subtitle: text(),
	value: text(),
	type: text().default("text").notNull(),
	status: text().default("draft").notNull(),
	source_hash: text(),
	translated_at: text(),
	reviewed_at: text(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_by: text(),
	component: text(),
});

export const site_domain_events = sqliteTable("site_domain_events", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	domain_id: text().references(() => site_domains.id, { onDelete: "set null" } ),
	event_type: text().notNull(),
	actor_type: text().default("system").notNull(),
	actor_id: text(),
	message: text(),
	before_state: text(),
	after_state: text(),
	metadata: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
});

export const site_domains = sqliteTable("site_domains", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	domain: text().notNull(),
	type: text().notNull(),
	role: text().default("secondary").notNull(),
	status: text().default("pending").notNull(),
	cloudflare_hostname_id: text(),
	cloudflare_hostname_status: text(),
	cloudflare_ssl_status: text(),
	ownership_validation_name: text(),
	ownership_validation_type: text(),
	ownership_validation_value: text(),
	ssl_validation_name: text(),
	ssl_validation_type: text(),
	ssl_validation_value: text(),
	dns_target: text(),
	dns_status: text().default("pending").notNull(),
	last_synced_at: text(),
	next_check_at: text(),
	retry_count: integer().default(0).notNull(),
	activated_at: text(),
	error_message: text(),
	metadata: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
});

export const site_entitlements = sqliteTable("site_entitlements", {
	id: text().primaryKey(),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	key: text().notNull(),
	value: text(),
	source: text().default("system").notNull(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const site_events = sqliteTable("site_events", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().references(() => business_locations.id, { onDelete: "set null" } ),
	actor_id: text().references(() => user.id, { onDelete: "set null" } ),
	event_type: text().notNull(),
	entity_type: text(),
	entity_id: text(),
	metadata: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const site_locales = sqliteTable("site_locales", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	locale: text().notNull(),
	label: text(),
	is_source: numeric().notNull(),
	status: text().default("draft").notNull(),
	fallback_enabled: numeric().default(sql`1`).notNull(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const platform_pageview_events = sqliteTable("platform_pageview_events", {
	id: text().primaryKey(),
	page_path: text().notNull(),
	referrer: text(),
	user_agent: text(),
	ip_hash: text(),
	session_id: text(),
	visitor_id: text(),
	duration_seconds: integer(),
	country: text(),
	region: text(),
	city: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const platform_analytics_daily = sqliteTable("platform_analytics_daily", {
	id: text().primaryKey(),
	date: text().notNull().unique(),
	page_views: integer().default(0),
	unique_sessions: integer().default(0),
	avg_session_duration: integer().default(0),
	unique_visitors: integer().default(0),
	pages_per_session: real(),
	returning_visitors: integer().default(0),
	top_pages: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
});

export const site_pageview_events = sqliteTable("site_pageview_events", {
	id: text().primaryKey(),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().references(() => business_locations.id, { onDelete: "set null" } ),
	page_path: text().notNull(),
	referrer: text(),
	user_agent: text(),
	ip_hash: text(),
	session_id: text(),
	duration_seconds: integer(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	visitor_id: text(),
	country: text(),
	region: text(),
	city: text(),
});

export const site_transfer_requests = sqliteTable("site_transfer_requests", {
	id: text().primaryKey(),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	from_organization_id: text().notNull(),
	to_email: text().notNull(),
	token: text().notNull(),
	status: text().default("pending").notNull(),
	initiated_by_user_id: text().notNull().references(() => user.id, { onDelete: "restrict" } ),
	accepted_by_user_id: text().references(() => user.id, { onDelete: "set null" } ),
	claiming_user_id: text().references(() => user.id, { onDelete: "set null" } ),
	claiming_organization_id: text(),
	message: text(),
	invited_plan: text(),
	invited_coupon: text(),
	invited_domain: text(),
	requires_payment: integer().default(0).notNull(),
	stripe_checkout_session_id: text(),
	payment_completed_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	completed_at: text(),
	last_reminder_at: text(),
	reminder_count: integer().default(0).notNull(),
	custom_domains_snapshot: text(),
	custom_domains_removed_at: text(),
	invited_interval: text().default("month").notNull(),
});

export const sites = sqliteTable("sites", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	theme_id: text().default("saya-theme-v1").notNull().references(() => themes.id),
	theme: text().default("saya").notNull(),
	slug: text().notNull(),
	subdomain: text(),
	custom_domain: text(),
	custom_domain_status: text().default("none"),
	primary_location_id: text(),
	public_url: text(),
	brand_name: text(),
	brand_description: text(),
	logo_url: text(),
	logo_asset_id: text().references((): AnySQLiteColumn => media_assets.id, { onDelete: "set null" } ),
	contact_email: text(),
	contact_phone: text(),
	source_locale: text().default("en").notNull(),
	default_currency: text().default("THB").notNull(),
	status: text().default("active"),
	plan: text().default("free"),
	onboarding_status: text().default("pending"),
	url_structure: text().default("location_subdirectories").notNull(),
	vertical: text().default("restaurant").notNull(),
	content_source: text(),
	media_source: text(),
	settings: text(),
	last_published_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	updated_by: text(),
	og_image_asset_id: text().references((): AnySQLiteColumn => media_assets.id, { onDelete: "set null" } ),
});

export const stripe_webhook_events = sqliteTable("stripe_webhook_events", {
	id: text().primaryKey(),
	stripe_event_id: text(),
	event_type: text(),
	status: text().default("pending"),
	payload: text(),
	error: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const themes = sqliteTable("themes", {
	id: text().primaryKey(),
	name: text().notNull(),
	slug: text().notNull(),
	version: text().default("1.0.0"),
	description: text(),
	status: text().default("active"),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
});

export const token_exchange_cache = sqliteTable("token_exchange_cache", {
	code: text().primaryKey(),
	state: text().default("pending").notNull(),
	response_body: text().default("").notNull(),
	http_status: integer().default(0).notNull(),
	created_at: text().notNull(),
	expires_at: text().notNull(),
});

export const translation_job_items = sqliteTable("translation_job_items", {
	id: text().primaryKey(),
	job_id: text().notNull().references(() => translation_jobs.id, { onDelete: "cascade" } ),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	target_locale: text().notNull(),
	entity_type: text().notNull(),
	entity_id: text().notNull(),
	location_id: text(),
	page: text(),
	field: text().notNull(),
	source_hash: text().notNull(),
	source_chars: integer().default(0).notNull(),
	status: text().default("queued").notNull(),
	error: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const translation_jobs = sqliteTable("translation_jobs", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	source_locale: text().notNull(),
	target_locale: text().notNull(),
	scope: text().default("site").notNull(),
	status: text().default("queued").notNull(),
	total_items: integer().default(0).notNull(),
	total_chars: integer().default(0).notNull(),
	estimated_input_tokens: integer().default(0).notNull(),
	estimated_output_tokens: integer().default(0).notNull(),
	estimated_credits: integer().default(0).notNull(),
	actual_input_tokens: integer().default(0).notNull(),
	actual_output_tokens: integer().default(0).notNull(),
	actual_credits: integer().default(0).notNull(),
	processed_items: integer().default(0).notNull(),
	failed_items: integer().default(0).notNull(),
	error: text(),
	created_by: text(),
	started_at: text(),
	finished_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const user = sqliteTable("user", {
	id: text().primaryKey(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer().default(0).notNull(),
	image: text(),
	phoneNumber: text(),
	phoneNumberVerified: integer().default(0).notNull(),
	role: text().default("user"),
	banned: integer().default(0),
	banReason: text(),
	banExpires: integer({ mode: "timestamp" }),
	createdAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
	updatedAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const verification = sqliteTable("verification", {
	id: text().primaryKey(),
	identifier: text().notNull(),
	value: text().notNull(),
	expiresAt: integer({ mode: "timestamp" }).notNull(),
	createdAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
	updatedAt: integer({ mode: "timestamp" }).default(sql`(unixepoch())`).notNull(),
});

export const work_requests = sqliteTable("work_requests", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().references(() => sites.id, { onDelete: "set null" } ),
	type: text().notNull(),
	title: text().notNull(),
	description: text(),
	status: text().default("pending").notNull(),
	priority: text().default("normal").notNull(),
	source: text().default("dashboard").notNull(),
	notes: text(),
	assigned_to: text().references(() => user.id, { onDelete: "set null" } ),
	completed_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const experiences = sqliteTable("experiences", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	location_id: text().notNull().references(() => business_locations.id, { onDelete: "cascade" } ),
	title: text().notNull(),
	slug: text().notNull(),
	tagline: text(),
	body: text(),
	image_asset_id: text().references(() => media_assets.id, { onDelete: "set null" } ),
	video_asset_id: text().references(() => media_assets.id, { onDelete: "set null" } ),
	images: text(),
	price: text(),
	price_amount: numeric(),
	duration_minutes: integer(),
	max_capacity: integer(),
	time_slots: text(),
	recurring_slots: text(),
	available_note: text(),
	status: text().default("active").notNull(),
	sort_order: integer().default(0).notNull(),
	featured: numeric().notNull(),
	featured_sort_order: integer().default(0).notNull(),
	seo_title: text(),
	seo_description: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	created_by: text(),
	highlights: text(),
	included_items: text(),
	what_to_bring: text(),
	meeting_point: text(),
	cancellation_policy: text(),
});

export const mcp_workspace_preferences = sqliteTable("mcp_workspace_preferences", {
	user_id: text().primaryKey().references(() => user.id, { onDelete: "cascade" } ),
	organization_id: text().references(() => organization.id, { onDelete: "set null" } ),
	site_id: text().references(() => sites.id, { onDelete: "set null" } ),
	location_id: text().references(() => business_locations.id, { onDelete: "set null" } ),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const google_analytics_connections = sqliteTable("google_analytics_connections", {
	id: text().primaryKey(),
	organization_id: text().notNull().references(() => organization.id, { onDelete: "cascade" } ),
	site_id: text().notNull().references(() => sites.id, { onDelete: "cascade" } ),
	connected_by_user_id: text().references(() => user.id, { onDelete: "set null" } ),
	provider_account_email: text().notNull(),
	encrypted_access_token: text().notNull(),
	encrypted_refresh_token: text().notNull(),
	scopes: text().notNull(),
	ga4_property_id: text(),
	ga4_property_name: text(),
	ga4_measurement_id: text(),
	search_console_site_url: text(),
	status: text().default("active").notNull(),
	expires_at: text(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
});

export const platform_content_components = sqliteTable("platform_content_components", {
	id: text().primaryKey(),
	content_type: text().notNull(),
	content_id: text().notNull(),
	type: text().notNull(),
	position: integer().default(0).notNull(),
	data_json: text().notNull(),
	created_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	updated_at: text().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`).notNull(),
	label: text(),
	status: text().default("active").notNull(),
	render_enabled: integer().default(1).notNull(),
	schema_enabled: integer().default(1).notNull(),
});
